### ISSUE TITLE
Windows not booting after doing the recovery steps

### ISSUE THREAD

**Issue by ThisAnonAgain** [namazso/SecureUxTheme#1]
- SecureUxTheme v1.1
- Windows 10 Pro (10.0.18362)
- Secure boot disabled
- Device Guard disabled
- No custom themes set yet
- SystemSettings hook was installed but not explorer hook

When installing, I had a message saying the Secureuxtheme dll was missing, despite being in the system32 folder.
After a reboot, the os stopped booting (but safe mode still worked)
Despite doing the recovery steps in the readme, the os was still refusing to boot.
I had to revert to an earlier restore point.

**Comment by namazso** [comment]
Could you please check if there are any Event Log entries related to this?
I'm specifically looking for an appcrash event involving dwm or winlogon.
Also, was it x64 or x86?

**Comment by ThisAnonAgain** [comment]
It's x64.
Are these events critical or error level? I'm having trouble finding anything related

**Comment by namazso** [comment]
it should be "Error" level, probably with event id 1000, but anything related would come handy. Some privacy settings may reduce log amount, but an entry should still exist.

**Comment by ThisAnonAgain** [comment]
I can see some windows explorer crashes and some other software crashes, but I don't think any of these are related

**Comment by namazso** [comment]
Cannot reproduce the issue on clean Windows 10 Pro 1903 18362.295 (x64) install. However I did notice some problems with the installer, namely the checkboxes aren't functioning correctly. Hook seems to be always installed for explorer, and never for SystemSettings. Do you have any software that might have caused conflicts, when we consider that explorer was also hooked?

**Comment by namazso** [comment]
Okay, I successfully reproduced the issue.
In order to cause this, the following steps must be taken:
1. Start setup
2. Click Install
3. Click Uninstall
4. Click Install
5. Ignore the fault that pops up
5. Reboot

After this, the system will hang at the boot screen.
I'll try to think of a solution for preventing this.

**Comment by ThisAnonAgain** [comment]
Nice work and nice passive agressive statement lol
Users are dumb I know.

**Comment by namazso** [comment]
Didn't want to make it sound passive agressive, english isn't my primary language.
Maybe you mean the fifth point? The button is literally called "Ignore", that's not something I made up.

**Comment by namazso** [comment]
I also clarified the recovery section a bit with a more step-to-step guide and a GIF that I should've really edited a bit before.
