### ISSUE TITLE
[Feature-Request] Support Command-Line

### ISSUE THREAD

**Issue by My3hab** [namazso/SecureUxTheme#100]
I would like SecureUxTheme to support the command-line, and having a parameter that installs SecureUxTheme silently.

I, - as a system administrator - am automate the SecureUxTheme installation on my systems. I tried and succeeded in setting up a silent install, but it's less functional and professional than using cmdline parameters, which are not supported by the SecureUxTheme executable.

I hope you will take this excellent suggestion into consideration. The issue #100! Awesome!

**Comment by OrthodoxWindows** [comment]
Alternatively, hooking Winaero ThemeSwitcher could work the same way, as Winaero ThemeSwitcher is made for command line use.

https://github.com/namazso/SecureUxTheme/issues/108

**Comment by namazso** [comment]
Closed in favor of #120
