### ISSUE TITLE
can't patch themes??

### ISSUE THREAD

**Issue by kakao3ri** [namazso/SecureUxTheme#101]
for some reason i can't patch the theme and the theme doesn't work.
![Untitled](https://user-images.githubusercontent.com/102885359/161406890-35ff6053-6027-4c0b-88e9-8efbddd19adb.png)

**Comment by namazso** [comment]
post the log (bottom right text view)

**Comment by kakao3ri** [comment]
> post the log (bottom right text view)

1648948284415 > Version v2.1.2
1648948284418 > Running on 10.0.22000 flavor F
1648948284420 > MainDialog: is_elevated 1
1648948284422 > Session user: Asus Process user: Asus
1648948284462 > UpdatePatcherState: file_has_content 1 file_is_same 1 file_error 0 is_loaded 1
1648948288808 > SelectTheme: pTheme->GetVisualStyle failed with 80070002
1648948295583 > SelectTheme: pTheme->GetVisualStyle failed with 80070002
1648948298015 > ApplyTheme(11)
1648948298019 > PatchThemeInternal(11)
1648948298026 > pTheme->GetVisualStyle failed with 80070002
1648948299356 > ApplyTheme: SetCurrentTheme returned 00000000

**Comment by namazso** [comment]
https://github.com/namazso/SecureUxTheme#q-selecttheme-ptheme-getvisualstyle-failed-with-80070002

**Comment by kakao3ri** [comment]
i have done that tho but it still doesn't work
![Screenshot 2022-04-03 091548](https://user-images.githubusercontent.com/102885359/161407074-64288e34-8713-4064-8821-f8ef7f2dd65a.png)

**Comment by namazso** [comment]
you clearly did not, i know for a fact BIB3 comes with a folder next to the .themes, containing the msstyle files

**Comment by kakao3ri** [comment]
idk bro. i tried a couple of times again and it still won't want to patch

https://user-images.githubusercontent.com/102885359/161407362-69c4c68a-fad5-4d70-87a2-7f4ae34530f9.mp4

**Comment by namazso** [comment]
# **COPY THE BIB3DM FOLDER TOO**

honestly I don't know how else I could tell at this point, it's as if you didn't even read neither the faq entry nor my previous message.

**Comment by kakao3ri** [comment]
bruh sorry im fucking dumb
