### ISSUE TITLE
mcafee deletes themetool.exe AS SOON AS IT DOWNLOADS

### ISSUE THREAD

**Issue by biggerinfinity** [namazso/SecureUxTheme#103]
subject.

**Comment by biggerinfinity** [comment]
![image](https://user-images.githubusercontent.com/101240040/168440661-a9b7330b-ecba-4f20-a932-e53ee5e401e6.png)

**Comment by namazso** [comment]
Solution: don't use McAffee. I reported this to their false positive email over a year ago and they didn't do shit. Such an incompetent company doesn't deserve users.
