### ISSUE TITLE
how to uninstall?

### ISSUE THREAD

**Issue by biggerinfinity** [namazso/SecureUxTheme#104]
Should I uninstall because I didnt click on hooklogonui while running theme tool? 
as per https://github.com/winthemers/windows-ricing#faq 
But your step by step guide namazso doesnt ask to do so?

**Comment by namazso** [comment]
It's just different ways of color reset fix. Read the `Help, what do these even mean?` button to understand it fully. `Rename DefaultColors` and `Hook LogonUI` are for the same thing but different methods with different bugs.

For uninstall, just use the `Uninstall` button.

**Comment by biggerinfinity** [comment]
should i just check the hooklogonui button and install without uninstalling first?

**Comment by namazso** [comment]
clicking `Install` will actually just attempt to uninstall, then run the install parts. So it really doesn't matter
