### ISSUE TITLE
Colors glitch in multiple places

### ISSUE THREAD

**Issue by senyehor** [namazso/SecureUxTheme#105]
Here is what I have in File explorer and Control panel with already two different themes I tried. Windows 2H21
![image](https://user-images.githubusercontent.com/78546473/171233092-dcac06a7-4b4d-4732-a0fc-483b8fce5e77.png)

**Comment by vinayakkuradia** [comment]
Please check this out! It might help...
[Consistent Dark Mode for All Apps, Windows 10 / 11 Customization + Paint Dark Mode](https://youtu.be/XSiSUiootRo?t=292)

**Comment by namazso** [comment]
Theme issue.
