### ISSUE TITLE
Context Menu on Windows 11 22H2 Build 22621.1 is not appearing well.

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [namazso/SecureUxTheme#106]
Context Menu on Windows 11 22H2 Build 22621.1 is not appearing well either in system tray's context menu or explorer context menu:

Safe Remove Context Memu
![image](https://user-images.githubusercontent.com/78225592/172030070-8f2a3811-6c37-4ff4-baed-69280c4b87e7.png)

Traffic Monitor Context Menu
![image](https://user-images.githubusercontent.com/78225592/172030217-8f539d71-aa70-4b2a-85b3-e80b7300acfd.png)

Desktop context menu
![image](https://user-images.githubusercontent.com/78225592/172030138-3208f282-89be-4be0-bf20-cbfbb1769f57.png)

Explorer Context Menu
![image](https://user-images.githubusercontent.com/78225592/172030159-63e57486-60a7-499c-8744-9144d580d155.png)

**Comment by namazso** [comment]
this looks like a theme problem, might check later

**Comment by MohammedMehdiTBER** [comment]
> 

It didn't happen when I used it on the stable version of Win11

**Comment by ShayBox** [comment]
Does anyone know how to manually fix this? Most themes don't support insiders, but if I can just disable context menu in the theme somehow it would be fine

**Comment by MohammedMehdiTBER** [comment]
> Does anyone know how to manually fix this? Most themes don't support insiders, but if I can just disable context menu in the theme somehow it would be fine EDIT: I just installed [Nilesoft Shell](https://nilesoft.org) (actually Rectify11) which replaces the context menu anyway 👍

Seems a nice program. It was suggested by CTT also.
