### ISSUE TITLE
File Explorer Autocomplete not working for custom themes

### ISSUE THREAD

**Issue by gdl-blue** [namazso/SecureUxTheme#107]
Windows 10 21H2. After applying custom themes autocomplete suggestions in the address bar does not work.

**Comment by remzmike** [comment]
I had the same problem and also traced it to Themetool, before seeing this issue. It doesn't happen with all themes. It also breaks autocompletion in file dialogs. And, it happens without any of the hook checkboxes selected. The problem goes away immediately when switching to another theme which doesn't cause the problem. No logout or reboot required.

**Comment by namazso** [comment]
In that case, it's a theme issue. Use a better theme, or try OldNewExplorer (idk if that helps, but it replaces some controls there)
