### ISSUE TITLE
[Feature Request] Add hooking for Winaero ThemeSwitcher

### ISSUE THREAD

**Issue by OrthodoxWindows** [namazso/SecureUxTheme#108]
Hello, 

I am writing batch scripts for switching from one theme to another (https://github.com/OrthodoxWindows/ThemeSwitcherScripts), and to achieve this, I use a tool called Winaero ThemeSwitcher (https://winaero.com/winaero-theme-switcher/), which allows you to change the Windows theme from the command line.

For the moment, my scripts are therefore not compatible with SecureUXTheme, because Winaero ThemeSwitcher is not hooked. Alternatively, I can also apply the theme from the command line using Explorer, but that involves hooking Explorer, which is not a solution for me, given the slowdown it causes.

**Comment by namazso** [comment]
Closed in favor of #120
