### ISSUE TITLE
Issue with UXThemePatcher/UltraUXThemePatcher or SecureUXTheme

### ISSUE THREAD

**Issue by ACNHChris** [namazso/SecureUxTheme#109]
Sorry not sure what the name is for UXThemePatcher, but recently I have been trying to get it to work on my Windows 10 Enterprise LTSC 2019. I'm not sure why it won't work but I wanna use a custom theme called ArcX.

_System Infomation_
- Windows 10 Enterprise LTSC 2019 
- Version: 1809 (OS Build: 17763.316)
- Storage: 318 GB HDD

I tried taking ownership of the files and then I ran the theme patcher and yet it still says the files haven't been patched yet.
Hope you can figure out the issue

**Comment by namazso** [comment]
Ok so first things first: Are you using SecureUxTheme, downloaded from this repository? If yes, please post logs from the bottom right corner.

**Comment by namazso** [comment]
Closed for lack of response
