### ISSUE TITLE
Question: what is the theme in the LogonUI fix screenshot?

### ISSUE THREAD

**Issue by Toby56** [namazso/SecureUxTheme#11]
The title explains it all! I wanna know what theme that is it looks good!

![Screenshot](https://raw.githubusercontent.com/namazso/SecureUxTheme/master/resources/logonui_comparison.png)

**Comment by namazso** [comment]
https://www.deviantart.com/niivu/art/Discord-Theme-for-Windows-10-793191161

**Comment by Toby56** [comment]
Btw thanks for the reply 😆
