### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Samyak-Bumb** [namazso/SecureUxTheme#110]
When I install **Hook explorer(!)** on Windows 10 and If I want to create new folder I press Ctrl+Shift+N My Explorer.exe Crashes and When I Uninstalled It Solved My Problem.

So What to do Should I Use and Recommend to peolpe Or Uninstall it.

**Comment by namazso** [comment]
The recommended way is to not hook explorer, the big warning popup is there for a reason. It's mostly useful for debugging really.
