### ISSUE TITLE
Fullscreening Windows is buggy

### ISSUE THREAD

**Issue by 1012zach** [namazso/SecureUxTheme#112]
Whenever I fullscreen a window, it's contents does not fullscreen like the window like the image bellow:
![image](https://user-images.githubusercontent.com/95945017/183722585-aab2f1fb-5ef8-4fca-a088-0d0ff1f38a92.png)

**Comment by namazso** [comment]
Works on my VMs, probably a theme issue, or maybe some other program messing up things.
