### ISSUE TITLE
[question] Is there a way to automatically switch themes?

### ISSUE THREAD

**Issue by AlNexus** [namazso/SecureUxTheme#114]
I really wanted to set a theme for light mode and dark mode at a certain time of the day, but the only way seems to be to just make a macro that opens the ThemeTool executable and changes the theme "manually". Wanted to know if there is a way to automatically switch, maybe a new feature in the tool itself or a third party software that can do that. For all I know, switching themes in the Personalization menu of Windows 10 settings doesn't work, which is expected, yeah?
The themes I use fully change Windows 10 (e.g. BIB3), including those win32 programs, IF that is the name. Though win32 programs are light mode by default so themes that change everything are not necessary for light mode)
Sorry for making this long. Annd thanks for developing this tool.

**Comment by OrthodoxWindows** [comment]
I am developing a series of scripts that have this function: https://github.com/OrthodoxWindows/ThemeSwitcherScripts

The development is not finished, but I am moving fast.

**Comment by namazso** [comment]
There will soon be, I'm making a C FFI interface exposing functionalities. Then you can just develop whatever tool you need for interaction. I'll also change licenses for the hook dll and the main functionality to LGPL, so that others can include it in other tools.

**Comment by namazso** [comment]
Closed in favor of #120
