### ISSUE TITLE
cocreateInstance Failed; hr 0x80040154

### ISSUE THREAD

**Issue by KaanAlper** [namazso/SecureUxTheme#116]
![image](https://user-images.githubusercontent.com/86665266/188515218-e9339cf6-b86d-4cf5-9ad2-760f98c7e52b.png)
![image](https://user-images.githubusercontent.com/86665266/188515231-1c1cb3c1-337b-4fab-9596-1cdd2dad9cca.png)

**Comment by namazso** [comment]
your OS is corrupted. do `sfc /scannow`

**Comment by KaanAlper** [comment]
> your OS is corrupted. do `sfc /scannow`

thanks dude it worked
