### ISSUE TITLE
Is there any chance that a command line interface can be implemented?

### ISSUE THREAD

**Issue by DoorsDev** [namazso/SecureUxTheme#118]
The title says it all. I rlly need it for a project and i hope someone has that figured out so that i can work on the other stuff

**Comment by OrthodoxWindows** [comment]
Especially since a tool exists for this, it is Winaero ThemeSwitcher. It would suffice to add the hock, in the same way as for the explorer or the settings application.

https://github.com/namazso/SecureUxTheme/issues/108

**Comment by namazso** [comment]
There won't be one, as I'm going with a C FFI interface instead. You will be able to write whatever command line interface you wish for that. Follow #120 for progress on that.
