### ISSUE TITLE
NSIS "ThemeValidSigner.exe"

### ISSUE THREAD

**Issue by 16thomja** [namazso/SecureUxTheme#12]
NSIS is looking for a program called "ThemeValidSigner.exe" in:
bin\Release\Win32\ThemeInvalidSigner.exe
which it can't find.

Any ideas?

**Comment by namazso** [comment]
I assume this is when building?
Anyways, build x86 for the project ThemeInvalidSigner and it should output that file

**Comment by 16thomja** [comment]
Ah, thanks
