### ISSUE TITLE
Patch and apply button greyed out.

### ISSUE THREAD

**Issue by itsabhinv** [namazso/SecureUxTheme#122]
I'm using Win-11 and it is 22H2 update. I have followed all the steps correctly but the button not working for patch and apply both.

![image](https://user-images.githubusercontent.com/103131808/193989877-bd83e9de-4f31-445c-9137-29d697b2f325.png)

**Comment by namazso** [comment]
https://github.com/namazso/SecureUxTheme#q-selecttheme-ptheme-getvisualstyle-failed-with-80070002
