### ISSUE TITLE
Patch and apply buttons not activating when using keyboard navigation

### ISSUE THREAD

**Issue by egasimus** [namazso/SecureUxTheme#125]
When I tab into the theme list and use the arrow keys to select a theme, the buttons to activate the theme remain greyed out; hitting Enter in the theme list just closes the tool.

**Comment by ItsProfessional** [comment]
Pull request #119 has fixed it, but the binaries for the latest commits have not been released in the releases section so you have to either use the latest development build from the actions tab in GitHub, or you have to wait for a stable release.
