### ISSUE TITLE
cant install Hook LogonUI

### ISSUE THREAD

**Issue by Be1zebub** [namazso/SecureUxTheme#129]
after reboot the "Hook LogonUI" checkbox is still unchecked
![image](https://user-images.githubusercontent.com/34854689/215293793-16db989a-d014-4971-8936-4f3937105449.png)
because of this task manager & other programms is unthemed
![image](https://user-images.githubusercontent.com/34854689/215293846-3083e64a-6c56-4d5d-83bb-349996df9cc4.png)

winver: win 10 22h2 build 19045.2486
theme: https://www.deviantart.com/niivu/art/Windows-11-for-Windows-10-882819383

**Comment by namazso** [comment]
Works as intended. The checkboxes apply to the next installation, for the current status see the groupbox above, which does say "Yes" for LogonUI hook.

**Comment by Be1zebub** [comment]
ok - thx, but task manager & other programms is un-themed.
should i open a new issue for this or we can continue here?
