### ISSUE TITLE
Is it possible to only apply the theme to the file explorer?

### ISSUE THREAD

**Issue by amerfarooq** [namazso/SecureUxTheme#13]
I've noticed that some themes give some applications weird colors that make it hard to use them. Is it possible to only apply the theme to the explorer and not to any of the installed applications?

**Comment by namazso** [comment]
no, this is literally in the FAQ
https://github.com/namazso/SecureUxTheme/issues/9#issuecomment-611897882

**Comment by namazso** [comment]
as for broken third party applications, I suggest you test them in the windows builtin black high contrast themes, and if they don't work there either, report it as a bug to the application developer, since that is a builtin feature of windows
