### ISSUE TITLE
Why are the ESTR, ESTRt macros used in the source code?

### ISSUE THREAD

**Issue by ItsProfessional** [namazso/SecureUxTheme#130]
I apologize if this is one of those newbie c++ questions that I should not be asking here, but I could not figure out why this exists here. Why is it required to encrypt and decrypt the text?

**Comment by namazso** [comment]
To reduce antivirus detections, so that I have to contact less AV companies before each release. Yes, AVs are this bad that this reduces initial detections by 60-70%.

**Comment by ItsProfessional** [comment]
Oh, that explains it. Thanks.
