### ISSUE TITLE
Virus Detected 

### ISSUE THREAD

**Issue by AnityaSharma** [namazso/SecureUxTheme#138]
I was downloading ThemeTool.exe, but my McAfee antivirus stopped the downloading because it has some kind of virus in it.

**Comment by namazso** [comment]
No it doesn't, McAfee just sucks. (Unless you downloaded from somewhere else, in which case grab it from here. There are known third party redistributions with malware.)

You're also invited to just compile it yourself.

For more info, see: https://github.com/namazso/SecureUxTheme#download-is-malware
