### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by imfalso** [namazso/SecureUxTheme#14]
I've installed it and it seems to work but if i shut off and then start again the pc, the theme is not applied anymore

**Comment by santinobch** [comment]
Same here, afeter rebooting the pc the theme settings reset. This happend to me with SecureUxTheme and UltraUxTheme. Other than that it works.

**Comment by santinobch** [comment]
Diving a little deeper i found that in the registry HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes , the theme is not properly set up, idk why. Will try to edit the registry manually and hope it works.
![image](https://user-images.githubusercontent.com/21242252/86048846-6fdb9400-ba51-11ea-9a50-75f211b7e783.png)

**Comment by santinobch** [comment]
I fixed it!, idk what it was but i basically changed any value that was pointing to an Aero .theme or .msstyles on regedit to my theme. Values are changed are located here:

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Themes

HKEY_USERS\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\ThemeManager

**Comment by namazso** [comment]
I'm not sure if that's a wise idea (maybe you won't be able to change back to default theme?), but this gave me a tip on what could be the problem. ThemeTool runs as x86, rather than native architecture, so there is a chance some registry keys go into the wow node rather than where they're supposed to

**Comment by santinobch** [comment]
Glad to help! uwu

**Comment by namazso** [comment]
probably fixed in v2.0
