### ISSUE TITLE
Bug: text boxes are full black and some areas white

### ISSUE THREAD

**Issue by Makezu90** [namazso/SecureUxTheme#140]
![explorer_0LsnyUH2xe](https://user-images.githubusercontent.com/89158176/232339703-8fde75d6-5445-4a91-9853-c788679da9b2.jpg)
![ApplicationFrameHost_ZaZyIgkMny](https://user-images.githubusercontent.com/89158176/232339714-96a9639d-247d-4169-a9d5-b4e4272f72f1.jpg)
![opera_fVqFIo6tBt](https://user-images.githubusercontent.com/89158176/232339725-b6506073-d060-4ee2-ae87-e9ff960ea9b1.jpg)

how i can fix these? in browser i can use force dark page but some webpages it looks annoying, however in apps its harder to do that. Happens atleast two different skins what i try use.

**Comment by namazso** [comment]
The first is theme issue.

As for the browser, you can override those colors with an userChrome.css (look it up)
