### ISSUE TITLE
Can't edit wiki via GitHub.

### ISSUE THREAD

**Issue by rokejulianlockhart** [namazso/SecureUxTheme#146]
At https://github.com/namazso/SecureUxTheme/wiki/Help:-Step-by-step-installing-SecureUxTheme-and-a-custom-theme,

> `C:\Windows\Resources\Themes` (or wherever your Windows is installed)

should be at least

`%SystemDrive%\Windows\Resources\Themes`

or better yet

`%SystemRoot%\Resources\Themes`

but I've been unsuccessful in ascertaining how to edit the wiki using [the relevant documentation](https://github.com/namazso/SecureUxTheme/wiki/Help:-Step-by-step-installing-SecureUxTheme-and-a-custom-theme#:~:text=c%3A%5Cwindows%5Cresources%5Cthemes%20(or%20wherever%20your%20windows%20is%20installed)). Perhaps the permissions are misconfigured for the repository?

**Comment by namazso** [comment]
It is intentionally worded like that because the average user has no idea what the funny percentage signs mean. Plus I'm not actually sure if installing Windows to non-C drive is even supported

**Comment by rokejulianlockhart** [comment]
@namazso, the average user shouldn't need to - just copy-pasting the path into `explorer` works like any other. Also, any gamer in existence has used `%appdata%` as a shortcut, so they're not generally unknown.

Despite that,

> I'm not actually sure if installing Windows to non-C drive is even supported

installation to a non-C drive is supported still. There are occasionally reasons to do it, although I can't recall any since I've never bothered to give myself that headache.

**Comment by namazso** [comment]
Edited.

And the perms are not misconfigured, if anyone can edit the wiki, GitHub makes it unindexable by search engines. So this is a tradeoff.
