### ISSUE TITLE
The theme doesn't apply to all the apps

### ISSUE THREAD

**Issue by DavideCanno** [namazso/SecureUxTheme#15]
Hi, i have a problem with SecureUxTheme. I apply the theme, (having it installed) and Chrome and Office and the Setting App (ms-setting:) use the same icons for minimize, closing and resizing, when on the Explorer it works as intended (even the taskmgr) See here:
https://imgur.com/a/mnn1aS7
https://imgur.com/a/K4muBDc
Thanks in advance
EDIT: Windows 1909 (build OS 18363.836) and even with rebooting the machine

**Comment by namazso** [comment]
These apps paint their own titlebars (that just happens to look like windows 10's), this is out of my control.
It would be possible to modify window flags to remove nonclient painting generally, however this would mean you wouldn't have the extra "features" of the custom titlebars, like the tabs on chrome, which would arguably make it completely useless. Plus, this is not something a theme patcher should be doing anyways.
Instead you could look for ways to disable custom titlebars in the programs themselves. After a quick search I found how to do this for [Chrome](https://winaero.com/blog/enable-native-titlebar-google-chrome/).

**Comment by DavideCanno** [comment]
Oh thanks a lot
