### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by luiza177** [namazso/SecureUxTheme#151]
Upon trying to build Release Win32, as instructed, I get the following errors:
```
LNK1181 cannot open input file 'ntdllp.lib'
```
I'm on Windows 11 22H2, Visual Studio 2022

**Comment by namazso** [comment]
Install the WDK

**Comment by luiza177** [comment]
I was able to build the Win32 Release, but now the ARM64 Release build fails. I get a warning now saying that the build tools for v143 cannot be found, even though VS installer says that they're installed. If I try to build anyway I get the following error:
```
MSB4018 The "VCMessage" task failed unexpectedly.
```
