### ISSUE TITLE
Using themes messes with the right click menu and breaks it for apps

### ISSUE THREAD

**Issue by Ylgnik** [namazso/SecureUxTheme#154]
Whenever I use any themes that are not windows default themes, the show more option in right click becomes different and when I go to an app (Like SSEEdit or Mod Organizer 2, I can't right click anymore, no menu shows up.

**Comment by Crocodile73** [comment]
Sounds like your using maybe 21H2 themes on 22H2 build. What OS are you on?

**Comment by Ylgnik** [comment]
Windows 11 Pro 22H2

**Comment by Crocodile73** [comment]
> Windows 11 Pro 22H2

Are you using Windows 11 22H2 themes. If you use older themes, they break amongst other things the right click menu.

**Comment by Ylgnik** [comment]
Ah looking at the page I got it from, it's for 21H2. My bad, and thank you for the help.
