### ISSUE TITLE
Blank Screen Windows 11 and Can't even boot

### ISSUE THREAD

**Issue by arthackrc** [namazso/SecureUxTheme#169]
I use catppuccin theme by nivu. But as i told on the title. Now i can't boot. How i can uninstall this now.

**Comment by Moist-Spoon** [comment]
the catppuccin theme is a windows 10 theme.

i think your best bet is trying to boot into safe mode. hopefully you created a system restore point.

**Comment by namazso** [comment]
https://github.com/namazso/SecureUxTheme/wiki/Help:-Login-loop-after-setting-a-theme
