### ISSUE TITLE
Error on SecureUXTheme.dll

### ISSUE THREAD

**Issue by Flaam** [namazso/SecureUxTheme#17]
Hello, i tried to use SecureUXTheme but this error appears, i tried to take ownership of the file too, is there a fix for this?
![immagine](https://user-images.githubusercontent.com/48182219/85379985-aa6a9b80-b53c-11ea-8994-da67178aac74.png)

**Comment by namazso** [comment]
try uninstalling, then rebooting, then installing again

seems like you tried to install it when it was already installed

**Comment by namazso** [comment]
probably fixed in v2.0
