### ISSUE TITLE
Files not patching

### ISSUE THREAD

**Issue by baferpro** [namazso/SecureUxTheme#18]
Nothing happens during installation, what to do?
All rights to the files are 100% granted.
Windows 10 Pro (2020).

**Comment by namazso** [comment]
they aren't meant to change, that's the point of this.
did it ask you to reboot after clicking install? does it not work after reboot?

**Comment by baferpro** [comment]
Got it, yeah. He asked. And, yes, the file is there.

**Comment by namazso** [comment]
probably fixed in v2.0
