### ISSUE TITLE
Include x64 and ARM in releases

### ISSUE THREAD

**Issue by MishaProductions** [namazso/SecureUxTheme#182]
Hi, can you please include x64 and ARM builds of ThemeDLL?

**Comment by namazso** [comment]
What should they be able to install? The current one is x86 because that runs on all architectures, and just picks the right thing to install. ARM64 only runs on ARM64, while x64 runs on x64 only, except on Windows 11 where it also runs on ARM64.

**Comment by MishaProductions** [comment]
Thanks for your response, but the problem that I am facing is that I have a x64 dll which needs to load themedll. However, you can't load 32 bit dlls in 64 bit dlls.

**Comment by namazso** [comment]
Fixed in 3.0.0
