### ISSUE TITLE
Confirmed to not be working on 23H2?

### ISSUE THREAD

**Issue by YnwLNE** [namazso/SecureUxTheme#187]
Don't see anyone talking about it. Sorry for a non-issue

**Comment by ReLyf47** [comment]
Windows 11 Pro 23H2 Build 22631.3672 not working
login loop instead

**Comment by kusalux** [comment]
Interesting it did work on 22631.3672 (@ReLyf47 did you check [this](https://github.com/namazso/SecureUxTheme/wiki/Help:-Login-loop-after-installing-SecureUxTheme)?). But now with .3737 it works only partly? Meaning the border still is being set but my dark background isnt anymore. I tried un and re-install and no change. It's unclear now, does SecureUxTheme need adaptions or the Theme?

**Comment by Crocodile73** [comment]
I'm running the same version as you. 22631.3737 and i have no issues with the theme applying. I will check the theme you linked to and see what i get.

**Comment by kusalux** [comment]
Any results? I tried few other things but except a clean install (that may just have time next weekend, not this) I am at a loss.

**Comment by kusalux** [comment]
I guess it is some windows bug then. Damn.

**Comment by YnwLNE** [comment]
After trying again every now and then it suddenly works, using the latest version and latest windows update lol

**Comment by namazso** [comment]
Fixed in 3.0.0
