### ISSUE TITLE
A theme is not showing up in ThemeTool

### ISSUE THREAD

**Issue by turbodude** [namazso/SecureUxTheme#194]
Hi, this is probably not directly a SecureUxTheme issue but please suggest what I could be missing here.
Using msstyleEditor I edited a couple of parameters in aero.msstyles (in order to center title bar text), saved it as a new theme, placed it next to the original file (`c:\Windows\Resources\Themes\aero\`), and the new theme is not showing up in ThemeTool. 

I restarted the system, the app says the patch is installed and loaded, but my theme isn't there. Nothing is hooked, I'm fine with applying themes via ThemeTool. 

Windows 11 23H2 22631.4112

**Comment by Crocodile73** [comment]
If you look in the themes folder, you will see a load of theme files. You need to have one for your theme. So copy Aero file to somewhere, change its name t your theme name. Last step open it with notepad and edit the name and path of your theme. Hope that makes sense.

**Comment by david-UT99** [comment]
this works on 11 ? ~ (it is currently broken on 10 and the developer doesn't seem to care about fixing it.

**Comment by turbodude** [comment]
> If you look in the themes folder, you will see a load of theme files. You need to have one for your theme. So copy Aero file to somewhere, change its name t your theme name. Last step open it with notepad and edit the name and path of your theme. Hope that makes sense.

thanks, that helped. I downloaded another custom theme and analyzed how it's structured and applied it here, the app recognized my theme.
However after applying it title bar text won't become centered anyway (Win 11 23H2), so go figure...
