### ISSUE TITLE
Does it work on windows 23h2 and soon 24h2?

### ISSUE THREAD

**Issue by BonziBUDDYVirus0499** [namazso/SecureUxTheme#195]
Hi! I'm wondering if SecureUXTheme works on windows 11 23h2 and soon, 24h2. I'm trying to apply a windows XP theme to my system.

**Comment by furquim87** [comment]
Based on my own experience: it will work on these versions IF you have previously installed the program before updating. I had to reinstall it after updating, and now my themes won't apply.

**Comment by KrazyDeinos** [comment]
@furquim87 Same for me, I had it working after 24H2, then i booted into safe mode, and after a normal reboot, the themes wont apply.
Do you or anyone know a workaround?

**Comment by KrazyDeinos** [comment]
thanks @furquim87 ! Method 2 worked for me on a hyper-v 24H2 VM and later on my machine.

Reinstalling SecureUxTheme with System Settings hooked:

    Open SecureUxTheme as an administrator
    Check "Hook System Settings"
    Hit install
    Reboot
    Try to apply a theme using the Windows Settings app (you'll still have to patch new themes using SecureUxTheme)


And thanks for reminding me of UltraUXThemePatcher, I had forgotten about that, always handy as a last resort!

**Comment by KrazyDeinos** [comment]
Hook system settings makes settings really slow, but not un-expected. So I opted for UltraUXThemePatcher , and it is working, can change theme via Settings.

In general 24H2 handles themes differently , WinAero Theme Switcher isn't working correctly, but I found another way to switch theme using cmd script.

**Comment by namazso** [comment]
Fixed in 3.0.0
