### ISSUE TITLE
theme tool exe file not starting even runned as administrator

### ISSUE THREAD

**Issue by plsanswer69** [namazso/SecureUxTheme#196]
im in windows 10 and i runned it as administrator (theme tool) and it didnt load/start

**Comment by djsolarix** [comment]
Same story Windows 10 Latest 22H2. The theme tool (Release v2.2.0) stopped opening suddenly. Tried admin mode, different folders, even compatibility modes and nothing worked. Also tried previous theme tool versions which all do the same , they wont open after hitting OK in the disclaimer window.

**Comment by david-UT99** [comment]
it's broken on 10. still waiting for dev to care..

**Comment by AlphaDeFcOn4** [comment]
Same problem !
Windows 10 Pro Build 19045.4894.
Theme tool is not opening anymore.

**Comment by david-UT99** [comment]
it seems like resetting or reinstalling windows is the only way to get it running again. i tried everything else.

i'm on 11 now, but even the 'only win 11 themes' aren't working properly, got white+black lines context menu when right clicking. so, i maybe coming back to 10 soon.

**Comment by AlphaDeFcOn4** [comment]
> it seems like resetting or reinstalling windows is the only way to get it running again. i tried everything else.
> 
> i'm on 11 now, but even the 'only win 11 themes' aren't working properly, got white+black lines context menu when right clicking. so, i maybe coming back to 10 soon.

New build and updates from windows broken Theme tool sadly we need a new version compatible.

**Comment by david-UT99** [comment]
bad news.. i went back to 10 cause i missed all my themes. today i got an old September update, not sure why it didn't install yesterday when i spent all day installing stuff, then i decided to install the optional preview and now the theme tool is broken again! this is really frustrating, there's NO WAY i'm spending 12 hours redoing this again. 
(hopefully uninstalling update or system restore helps).

**Comment by namazso** [comment]
Fixed in 3.0.0
