### ISSUE TITLE
Windows 10 native transparency issue

### ISSUE THREAD

**Issue by innuendo33** [namazso/SecureUxTheme#2]
Hi Namazso and gratz for your nice work .
That said , I noticed something related to secureuxtheme : 

On latest build 1903 x 64 , when applying your app it seems windows transparency even enabled doesn't work anymore ( windows settings / start menu and taskbar display with plain color .

Blur disappears . Compared to ultraux theme patcher transparency is back .

Have to test on other rig though. 

Regards

**Comment by namazso** [comment]
Interesting, on my (up to date, 1903) VM it works both without and with applying a custom theme:
![image](https://user-images.githubusercontent.com/8676443/65421460-4f601880-ddf3-11e9-85ff-e668a295669d.png)
![image](https://user-images.githubusercontent.com/8676443/65421465-5555f980-ddf3-11e9-95d7-16e91c4851b9.png)
please do test on another computer

**Comment by innuendo33** [comment]
Thanks for reply ! you right , my other rig up to 18362.356 has no issue using secureuxtheme compared to my main rig . Maybe this one up to 18362.295 has a corrupted data . Gonna investigate :) 
Regards !

**Comment by innuendo33** [comment]
Hi 
Well , still goes on my main rig ( 18362.356 ) I don't figure what's going on with although transparency still working on my other comp. 
![Snap14](https://user-images.githubusercontent.com/52549860/65497845-358a0880-debb-11e9-9e95-3cfb2030549a.png)

**Comment by namazso** [comment]
is this with or without a custom theme?
without one everything should behave almost exactly the same as without the patcher installed, the only actual behavior change is when enabling logonui fix.
can you check if the problem still exists without installing the logonui fix? (uninstall, then install without fix, then reboot)

**Comment by innuendo33** [comment]
I tried both without and with custom theme. And the screenshot was without installing logonui fix .
This one is made on same rig with ultraux theme patcher and everything works fine, this is driving me crazy :) 
yes for not focus state I noticed that 
One detail too: my main rig run an US windows 1903 and the other one working fine with secureux is a french windows 10 . That's weird :/ 
![Snap14](https://user-images.githubusercontent.com/52549860/65503571-7850de00-dec5-11e9-99cf-ee5f19bf4ef7.png)

**Comment by innuendo33** [comment]
I'd like to know please if you also get notification center transparent too beside taskbar/ startmenu ? 

on the "working " computer I noticed notif center doesn't have transparency at this location

**Comment by namazso** [comment]
![image](https://user-images.githubusercontent.com/8676443/65592943-1359be80-df7f-11e9-9155-ac31a09b9fdb.png)
behaves pretty normal on my vm

**Comment by innuendo33** [comment]
ok ! I saw on forums some transparency issues too with 1903 like I have , I will test further when having time ( switch display drivers etc ) 
Regards

**Comment by innuendo33** [comment]
Ok , I can confirm on my main rig , native transparency issue related with secureuxtheme ( whatever version I test and logonfix on or off ) 

![2](https://user-images.githubusercontent.com/52549860/65640444-b0057600-dfea-11e9-839b-1fd7600a72f5.png)
![1](https://user-images.githubusercontent.com/52549860/65640453-b4ca2a00-dfea-11e9-8b20-3c60330464b1.png)

Very weird :/ gonna try with newest drivers nvidia ( my other comp run ati drivers )

**Comment by namazso** [comment]
Can you also check Event Viewer for suspicious entries?
Without LogonUI fix nothing is altered in a way it would change any behavior (only a disabled signature check), so my only guess is that maybe I crash dwm or winlogon for some reason..

**Comment by innuendo33** [comment]
No issue on event viewer :/ Sadly I could identify or solve the pb if I make a new clean install to get rid of all custom settings beside but for now I don't feel any courage to do that . I even tried to restore a non us image system in vain: same issue with secureux. Workin fine on my laptop for work though .. 
Drives me crazy ah ah 
btw the difference between my 2 comps is the working one has uefi bios and the other is set with legacy bios . Could it be the reason ?

**Comment by namazso** [comment]
Interesting, I'll tried some guesses at reproducing the issue.
The UEFI/BIOS thing gave me a tip that maybe its about HVCI/VBS so I went ahead and enabled every security feature (VBS, HVCI, Secure boot, Memory integrity) that could possibly cause problems, but still didn't manage to break transparency, so I'm kinda out of guesses
![image](https://user-images.githubusercontent.com/8676443/65778350-4776e000-e135-11e9-8871-e9ef61e6b2b0.png)

**Comment by namazso** [comment]
Could you try one more thing?
Install SecureUxTheme, don't reboot, replace SecureUxTheme.dll with [this](https://share.riseup.net/#7CWhCcyOHmeVaAwBrhIn6A) ([source](https://share.riseup.net/#Pe5l5BSE_hU47sBwoJsg3w)) empty application verifier dll that shouldn't do anything at all, then reboot. 
This would tell me whether it is a problem with avrf / injection / some code integrity check, or it has something to do with the themes

**Comment by innuendo33** [comment]
Ok I give you feedback , during week end when free time :) 
Thanks !

**Comment by innuendo33** [comment]
Made a fast test ! 
still the same wow . With your file beside the orignal one and uninstall put back native transparency .:/
![Snap1](https://user-images.githubusercontent.com/52549860/65781976-01c61180-e14d-11e9-925f-ad6de842bd4f.png)

**Comment by namazso** [comment]
you couldn't even have used a custom theme, this dll is literally an empty stub that doesn't enable custom themes whatsoever. It doesn't change anything at all in fact, other than loading.

Do you use any antivirus products by any chance?

**Comment by innuendo33** [comment]
The native one Windows defender

**Comment by innuendo33** [comment]
oh and I noticed I have a warning popup message publisher unknown " before allowing , could it be that ?

**Comment by namazso** [comment]
No, that's normal, that's just because I don't have a code signing certificate (these things cost money) and isn't important.
I already test with Defender enabled. I also just tested it on my main computer (so I can make sure it isn't nVidia drivers or something) and couldn't reproduce. I also tried manually killing dwm/winlogon to simulate a crash, with no result. Could you try removing the relevant registry keys for "dwm.exe" and "winlogon.exe" in two independent tests to see which one causes the problem? Open up regedit at `HKEY_LOCAL_MACHINE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\`, delete values VerifierDlls and GlobalFlag from the key for dwm.exe / winlogon.exe

**Comment by innuendo33** [comment]
hm problem is I don't have any of those values 

![Snap2](https://user-images.githubusercontent.com/52549860/65784134-aea28d80-e151-11e9-8153-d2e3db2290e4.png)

**Comment by namazso** [comment]
Is this while having SecureUxTheme installed? because then it should always be present else it wouldn't cause anything to happen (at all)

**Comment by innuendo33** [comment]
So it's my rig without SecureUX installed ( windows 10 x 64 pro ) 
and I checked on the laptop where secureux is working , regedit is the same ( note it runs w10 x64 HOME ) 
Strange 

Could you attach some exported keys of your registry to test ?

**Comment by namazso** [comment]
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dwm.exe]
"GlobalFlag"=dword:00000100
"VerifierDlls"="SecureUxTheme.dll"

```
home shouldn't affect anything

**Comment by innuendo33** [comment]
Hi namazso

Let me first say .. you the man :) 

Ok so let feedback what I did with your help on my non working computer:

1)Installed SecureUX with logon UI fix then reboot
2)Checked the registry entries and my bad there , keys you talked about are registered ( dwm and winlogon ( both flags " global" and " dll" ) 


At that time, native transparency is screwed.

3) DELETE both flags in DWM registry section then I rebooted

4) tada ! native transparency back and I ran hooked personnalization + fix signature to apply a custom theme and everything works like my laptop computer.

So my question , could you make a version of secureUX which doesn't register in DWM section to avoid delete manually those entries ? 

Best regards you find out the issue :) though I don't figure why it happens like that on my main computer compare to the laptop.

**Comment by namazso** [comment]
Okay, I have absolutely no idea why anything at all works with no DWM hooks (confirmed this on my VM), even less more so about how this fixes the transparency issue that I couldn't in any way reproduce.

I'll check which windows versions don't require DWM hooks (pretty sure some do) and modify the installer to skip installing it for the ones that don't need it.

Thanks for all this

**Comment by innuendo33** [comment]
You welcome , at the moment and till you relases such build , I 'm using a reg file to merge after install and fix  .

**Comment by innuendo33** [comment]
Well Namazso , important detail I just found 

I tested delete both reg entries in my laptop ( same DWM ) and secureUX still works ( with custom theme with native transparency  after reboot wow 

Does mean that installer don't need to register at that location ? If so you don't need to make an option to skip that just register the winlogon part with secureUX.dll 

![Capture](https://user-images.githubusercontent.com/52549860/65830560-dceaaf00-e2b0-11e9-8f6b-9a42f0e3943b.PNG)

**Comment by namazso** [comment]
yes that's correct, this is why I tested on my VM. I plan to automatically decide whether to install for DWM or not, which requires me to do tests on my various version Windows VMs.

**Comment by namazso** [comment]
It seems to work even on Windows 8.1 without placing DWM hooks. I'll just remove it alltogether, and add it back if someone complains it broke

**Comment by innuendo33** [comment]
Many thanks for the update :)
