### ISSUE TITLE
Not exactly an Issue, but a question: Does this have the potential of accidentally getting detected on anti-cheats?

### ISSUE THREAD

**Issue by jakem2** [namazso/SecureUxTheme#20]
Sorry if this is a super dumb question but I get a little anxious with stuff like this.
As the title says, is it possible this would accidentally be detected as a cheat/hack/mod in games?

**Comment by namazso** [comment]
Technically, anything you run on your machine has that potential.
That being said, injecting into winlogon or logonui is quite useless for cheating purposes so I'd say this doesn't have much more chance of being detected as such compared to anything else.

**Comment by jakem2** [comment]
Thanks for the insight!
I guess I was comparing it to the traditional method (UltraUX) but got paranoid when I heard inject aha. It's been awhile since I've themed so just wanted to be sure, so thanks again!

**Comment by namazso** [comment]
If anything the traditional is worse, since the patched (and thus unsigned) file is loaded into the game process. This shouldn't touch anything beyond winlogon.exe and logonui.exe (when locked)

**Comment by jakem2** [comment]
Damn really? I wouldn't have thought that at all. I assume its locked by default then?

**Comment by namazso** [comment]
I meant logonui.exe only executes when you lock your machine (with Win+L). And the patches are only applied if you ticked LogonUI fix.
