### ISSUE TITLE
can't get passed disclaimer on setup

### ISSUE THREAD

**Issue by ILudw1g** [namazso/SecureUxTheme#201]
gives disclaimer then the exe doesnt open after that prompt
![image](https://github.com/user-attachments/assets/6d2cd46c-0484-4401-b5b2-321a6117b6c3)

**Comment by AlphaDeFcOn4** [comment]
Same problem...
September update from windows broke the Themetool.exe
We need a new version. No fix yet.

**Comment by namazso** [comment]
Is this on Windows 11?

**Comment by ILudw1g** [comment]
me on win10

**Comment by AlphaDeFcOn4** [comment]
> Is this on Windows 11?

Not working on Windows 10 build September.
Windows 11 I don't know...

**Comment by david-UT99** [comment]
> Is this on Windows 11?

yes, it broke on windows 11 after i installed the iso from microsoft and when i updated 23h2. i didn't even try 24h2 which people say it's broken.
then as i wrote on the other thread, i went back to 10 and updated some more and it broke again. but i used system restore to a few hours earlier & it's working fine now. (i disabled update besides defender).

**Comment by namazso** [comment]
Fixed in 3.0.0
