### ISSUE TITLE
Using ThemeDll in PowerShell

### ISSUE THREAD

**Issue by Anninzy** [namazso/SecureUxTheme#205]
I'd like to apply a theme using PowerShell, and I'm not too sure on how to go about this. After some googling and making attempts for hours, I didn't get any closer.

[This](https://github.com/namazso/SecureUxTheme/discussions/156#discussioncomment-6897790) led me to Google which gave [this post](https://www.leeholmes.com/powershell-pinvoke-walkthrough/), but that didn't help too much.
I'm not sure what [this](https://github.com/namazso/SecureUxTheme/issues/178#issuecomment-1962751151) means.

I tried
```
[reflection.assembly]::LoadFile("$HOME\SecureUxTheme-amd64\ThemeDll.dll")
```
Which gave
```
Exception calling "LoadFile" with "1" argument(s): "The module was expected to contain an assembly manifest.
(Exception from HRESULT: 0x80131018)"
```

I also attempted
```
Add-Type -Path "$HOME\SecureUxTheme-amd64\ThemeDll.dll"
```
Which gave basically the same error
```
Add-Type : Could not load file or assembly 'file:///...\ThemeDll.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
```

It'd be great if you can offer some help, thank you.

**Comment by namazso** [comment]
ThemeDll is not managed, you shouldn't be loading it for reflection but should be PInvoking it. The post you linked works perfectly:


```
Add-Type @"
    using System;
    using System.Text;
    using System.Runtime.InteropServices;

    public class Kernel32
    {
        [DllImport("kernel32", CharSet = CharSet.Unicode, SetLastError = true)]
        public static extern IntPtr LoadLibrary(string librayName);
    }

    public class ThemeDll
    {
        [DllImport("ThemeDll.dll")]
        public static extern uint secureuxtheme_get_state_flags();
    }
"@

$ScriptPath = Split-Path -Parent $MyInvocation.MyCommand.Definition

[void]([Kernel32]::LoadLibrary("$ScriptPath\ThemeDll.dll"));

$Flags = [ThemeDll]::secureuxtheme_get_state_flags();
Write-Host ("Flags: {0:X}" -f $Flags)
```

This will print the appropriate bitflags for your system.

**Comment by e-t-l** [comment]
> Thanks for the swift reply! I'm quite unfamiliar with this, which is why I couldn't figure out how to apply the post. I'll try to figure the rest out. If I can't, hopefully it'd be fine to come back to you. Thanks again.

Did you write a working script to set a theme? If so can you share it?

**Comment by chip33** [comment]
@e-t-l 

Hi, if you get one working could you kindly post it here as it would be great to have a working example. 
Thanks
