### ISSUE TITLE
Where is x64 bit download?

### ISSUE THREAD

**Issue by Milicent-Heeler** [namazso/SecureUxTheme#219]
### I want x64 download
If SecureUXTheme is amd64, arm64 and x86 how can it support windows 11? Windows 11 is **x64 only** and I run windows 11. Do I download x86 even though I am x64 bit? Please reply back. 
Thanks in advance.

**Comment by rubberocket** [comment]
x64 = amd64.

**Comment by Milicent-Heeler** [comment]
> x64 = amd64.

Thanks!

**Comment by namazso** [comment]
As a sidenote, Win 11 is not x64 only, they had an entire PR thing for arm64: https://www.microsoft.com/en-us/windows/copilot-plus-pcs

**Comment by Milicent-Heeler** [comment]
> As a sidenote, Win 11 is not x64 only, they had an entire PR thing for arm64: https://www.microsoft.com/en-us/windows/copilot-plus-pcs

Yeah, but I have x64 bit.
