### ISSUE TITLE
LoginUI Fix not working

### ISSUE THREAD

**Issue by JoeAteTheBeans** [namazso/SecureUxTheme#22]
Whenever I lock my computer some colours are replaced with windows defaults. I know that the logonUI fix is supposed to fix this issue but for some reason it's still occurring. I have uninstalled the program twice now but to no avail.

Here's what it looks like:
![Screenshot 2020-07-27 162254](https://user-images.githubusercontent.com/60623226/88560721-64ff2980-d026-11ea-82bf-16ae669e4bf9.png)

It's worth noting that I am using a Windows Insider build:
![Screenshot 2020-07-27 163041](https://user-images.githubusercontent.com/60623226/88560898-9f68c680-d026-11ea-87d4-55204838ea0a.png)

**Comment by namazso** [comment]
I'll test this in a VM.
meanwhile, you can try (backing up, then) deleting `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\DefaultColors` as a solution, if that doesn't exist windows setting colors will just silently fail

**Comment by JoeAteTheBeans** [comment]
Deleting that registry key worked, thanks for your quick response.

**Comment by namazso** [comment]
Confirmed and now fixed in newest version.
