### ISSUE TITLE
Building Issue

### ISSUE THREAD

**Issue by donaldterance** [namazso/SecureUxTheme#23]
Great software! applied a downloaded theme with ease.
I'm trying to debug in vs, just to follow along and see how the software works. 
Everything builds except the SecureUxTheme project. 
![image](https://user-images.githubusercontent.com/12154265/89132508-4abbc480-d4da-11ea-8f6a-84689f09f90b.png)

Is there a missing function or something I missed in the clone?

**Comment by namazso** [comment]
Debug builds don't really work, because crt-less environment. you will have to stub out those to make a debug build.

**Comment by namazso** [comment]
plus if you actually want to see the debug messages, you will need a kernel debugger and a VM, because debug messages don't really work before a process is created - when the code runs.

**Comment by namazso** [comment]
fixed in 4119f33ed75df0de8a2dda659bba4c443bd83030
