### ISSUE TITLE
ThemeTool.exe doesn't launch on Win 8.1

### ISSUE THREAD

**Issue by Lucas559-noob** [namazso/SecureUxTheme#26]
When I execute it, it say this
`unable to locate the entry point for the RtlGetTokenNamedObjectpath procedure in the dynamic link library "path of .exe"`

**Comment by namazso** [comment]
what OS version?

**Comment by Lucas559-noob** [comment]
> what OS version?

windows 8.1 version 6.3 build 9600

**Comment by namazso** [comment]
confirmed, i accidentally broke win8.1 support last update.
for now you can just use the previous release, meanwhile i'll try to figure out something.

**Comment by namazso** [comment]
fixed in v2.1
