### ISSUE TITLE
not downloading the patcher

### ISSUE THREAD

**Issue by Jxkob123** [namazso/SecureUxTheme#27]
When i press the download button it downloads the "Theme Tool" and not the Patcher. I cant use it with no patcher. How can i download the patcher then? Thanks

**Comment by namazso** [comment]
theme tool contains the patcher and installer since last release

**Comment by Jxkob123** [comment]
but how do i get it then? It says no Patcher installed.

**Comment by namazso** [comment]
run as admin and click install
