### ISSUE TITLE
Patch and Apply buttons greyed out 

### ISSUE THREAD

**Issue by jojoharry16** [namazso/SecureUxTheme#29]
To the best of my knowledge I followed all the steps, however the buttons are still greyed out.

I installed all the hooks, but the buttons remained the same and this is the log displayed:

```
1602078259563 > Running on 10.0.19041 flavor F
1602078259564 > MainDialog: is_elevated 1
1602078259565 > Session user: myself Process user: myself
1602078259573 > UpdatePatcherState: file_has_content 1 file_is_same 1 file_error 0 is_loaded 1
1602078266430 > SelectTheme: pTheme->GetVisualStyle failed with 80070002
1602078267328 > SelectTheme: pTheme->GetVisualStyle failed with 80070002
```

There is also a (!) next to the text "Hook explorer"

Any and all help appreciated

**Comment by jojoharry16** [comment]
Update: while I was writing this issue the Apply button became available, but the Patch button is still greyed out and the log "GetVisualStyle failed" only shows up with some custom themes I installed

**Comment by namazso** [comment]
are you sure your problem isn't this:
https://github.com/namazso/SecureUxTheme#q-selecttheme-ptheme-getvisualstyle-failed-with-80070002

**Comment by jojoharry16** [comment]
Thanks for the reply, but I'm sure I moved them to the correct folder. 
I'm happy to get more logs or details, just let me know where and how to get them :)

**Comment by namazso** [comment]
Could you just post your entire Themes folder? There isn't much more to logs, and your windows version is one of the tested ones. It seems like Windows can't figure out the style path from the theme.

**Comment by jojoharry16** [comment]
https://1drv.ms/u/s!AqLIlR_sYGQU4EIGLIKBKzJ-KXkg?e=MuxIOC

**Comment by namazso** [comment]
weird, all themes in your folder work perfectly on my VM of the same feature update, even after applying latest updates. I'd say it's permission issue but you're running it as admin so it shouldn't be, unless you did something very wrong to the permissions which i doubt. 

My only remaining guess is that maybe you're running some sort of antivirus / sandboxing solution?

**Comment by Kdizzle8d8** [comment]
I have the same error except only the patch button is greyed out. and the themes wont work properly without being patched

**Comment by namazso** [comment]
@Kdizzle8d8 that condition should only be possible if the theme is already patched. Are you sure that's not the case?

**Comment by stashymane** [comment]
Can also report this - apply was not present for a few attempts, now only patch is greyed out. I have to patch the same themes on my desktop, but on my laptop it's not possible. Applying these themes changes only the color scheme.

**Comment by stashymane** [comment]
Figured it out - in my case, I just placed the themes in Windows/Resources, not Windows/Resources/Themes.

**Comment by jetrosut** [comment]
I am having the same issue and the .theme file I want to apply is located in C:\Windows\Resources\Themes. The patch button is always greyed out for all themes.

![themeto](https://user-images.githubusercontent.com/71877689/104990894-6a846d80-59d2-11eb-9516-18fbd97fc02b.png)

**Comment by namazso** [comment]
@jetrosut could you post the logs from the lower right part?

**Comment by hqrmful** [comment]
my path and apply buttons are also greyed out and all my themes are in the right place please help :(

**Comment by hqrmful** [comment]
here is the logs 1611041763087 > Version v2.1.2
1611041763087 > Running on 10.0.19042 flavor F
1611041763088 > MainDialog: is_elevated 1
1611041763088 > Session user: Moki Process user: Moki
1611041763105 > UpdatePatcherState: file_has_content 1 file_is_same 1 file_error 0 is_loaded 1

**Comment by hqrmful** [comment]
ha! nvm i didnt move the folders that came with the theme files. my bad!

**Comment by CraftingTable629** [comment]
I have the same problem too...
[https://ibb.co/WPg1C67](url)

Error message below:
43 flavor F
1654779697946 > MainDialog: is_elevated 1
1654779697946 > Session user: User Process user: User
1654779697964 > UpdatePatcherState: file_has_content 1 file_is_same 1 file_error 0 is_loaded 1
1654779699821 > SelectTheme: pTheme->GetVisualStyle failed with 80070002

**Comment by namazso** [comment]
@CraftingTable629 you did it wrong. You simply copy this all into `C:\Windows\Resources\Themes`:

![image](https://user-images.githubusercontent.com/8676443/172894969-dfd5b2fa-8609-4bcf-8bc9-0e0308ab1a95.png)

and keep the file structure as-is.
