### ISSUE TITLE
Windows 10 X64. Login loop after installing theme.

### ISSUE THREAD

**Issue by Xeddius** [namazso/SecureUxTheme#3]
My Win10 install is no longer usable after installing a theme and using SecureUxTheme, I followed the steps provided and while one theme worked just fine, I wanted to use another dark theme that I downloaded from the site where your preview theme is from (And yes, I checked, it is a Windows 10 theme). I installed everything (aside from explorer hook because I didn't want to take the risk) and rebooted and upon installing the theme and setting it using "hooked personalization" the screen turned black and I was never able to get back into Windows 10. I followed the recovery steps to the letter and upon reboot I am now stuck at an infinite login loop, enter password - login screen returns - enter password - login screen returns, etc.

Is there any way to fix the loop or am I just going to have to abandon my current install? I don't have restore points, I don't have a recovery image, etc. If there isn't a way to fix this I'm probably just going to switch to linux until I can make a new Win10 usb and never touch any theme related things again as it always ends in having to re-install windows for me.

**Comment by namazso** [comment]
sounds like a problem with the theme, but feel free to provide windows version and link to theme so I can confirm.
as for recovery, there is a section specifically for this scenario in the readme: https://github.com/namazso/SecureUxTheme/blob/master/README.md#recovery
this would reenable signature check which would make it fall back to default theme.
After that you can remove the offending theme and reinstall SecureUxTheme if you want to.

**Comment by Xeddius** [comment]
I followed the recovery steps and did everything as you had mentioned but was not able to recover Windows 10 1909. The theme was [Katy dark](https://7themes.su/load/windows_10_themes/temnye/katy_dark/34-1-0-1107). I've since deleted my Windows partition and have switched to Manjaro. Luckily I keep anything important on a separate drive so nothing vital was lost and most of my games work fine with Lutris and Steam.

**Comment by namazso** [comment]
Well, the theme page says it only works on 1511 so not sure what you expected on 1909.
I'll check if recovery works in systems broken this way, I only ever checked with broken SecureUxTheme.

**Comment by namazso** [comment]
Well, can't get it as broken as you did, it's only about as broken as you'd expect from a theme made for a 4 years older version of Windows 10.
One comment on the site also says apparently deleting the offending theme from Resources should work too.
![image](https://user-images.githubusercontent.com/8676443/67855951-6c32ee80-fb0b-11e9-80fe-5eda4a6f3760.png)

**Comment by namazso** [comment]
Installing this 4 year outdated theme on 1909 indeed caused login loop for me too.
Doing the steps written in the comments under the site you linked (booting into safe mode and changing theme) worked for recovery though.
Might consider adding this to the readme, although it is clearly not a problem with SecureUxTheme.

**Comment by Clemens-E** [comment]
Even tho this is not a problem with SecureUxTheme, I think it should be added into the recovery.md.
Why? I just had the same problem and this issue helped me, but others might not search for it
