### ISSUE TITLE
On 20H2 does not seem to go

### ISSUE THREAD

**Issue by xzj8b3** [namazso/SecureUxTheme#30]
On 20H2 does not seem to go, I downloaded zipper but I do not see an exe at 64

**Comment by xzj8b3** [comment]
![2020-10-10](https://user-images.githubusercontent.com/26720956/95656524-3fef6280-0b0f-11eb-88e9-0e30325807c1.png)


????? exe 64???

**Comment by namazso** [comment]
You downloaded the repository. Download the release (on the right, or linked in the readme) if you want binaries. The repository is for ones who wish to compile it from source.
