### ISSUE TITLE
can't apply a theme on themeTool

### ISSUE THREAD

**Issue by Fliw** [namazso/SecureUxTheme#31]
hi, im new to customizing windows UI/UX, the problem appear when i apply a custom theme. the error log look like this : 

```
1603211774606 > pTheme->GetVisualStyle failed with 80070002
1603211775545 > ApplyTheme: SetCurrentTheme returned 00000000
```

the procedure i've tried : 

- download and start themeTool.exe and run as admin.
- install patcher
- install hook explorer and hook system setting.
- copying the theme to windows\resource\themes.
- restart and applying the theme.

my windows version is `10.0.19041 Build 19041`

**Comment by namazso** [comment]
can you post your Themes folder? Also your resolution and scaling.

**Comment by Fliw** [comment]
![image](https://user-images.githubusercontent.com/56640907/96666251-f0b3f800-1380-11eb-9840-57fb1257f0f0.png)
here is my themes folder

and here is my resolution and scaling
![image](https://user-images.githubusercontent.com/56640907/96666308-0aedd600-1381-11eb-84f8-14b73f77514b.png)

**Comment by Fliw** [comment]
```
1603248957655 > ApplyTheme: SetCurrentTheme returned 00000000
1603248959676 > ApplyTheme(33)
1603248959677 > PatchThemeInternal(33)
1603248960164 > ApplyTheme: SetCurrentTheme returned 00000000
```

it's works! it's only about the directory ✌🏻 i'll close this issue now, thank you!
