### ISSUE TITLE
Not working in windows 10 October Update

### ISSUE THREAD

**Issue by Pradeepcctns** [namazso/SecureUxTheme#33]
Not working in windows 10 October Update
![SharedScreenshot](https://user-images.githubusercontent.com/72693188/98099874-1deec300-1eb6-11eb-99d6-8054069202f5.jpg)
![winver](https://user-images.githubusercontent.com/72693188/98099885-21824a00-1eb6-11eb-8bb5-3e0b53ce7a74.jpg)

--my windows version--
Edition	Windows 10 Home Single Language
Version	20H2
OS build	19042.572

**Comment by namazso** [comment]
It says right there you haven''t installed it. If you don't install, it doesn't work.

**Comment by Pradeepcctns** [comment]
I trying to install but when clicked on setup, the install button not working....install button seems like as shown in the screenshot provided above
Please tell me how to solve this...

**Comment by namazso** [comment]
run it as administrator...

**Comment by Pradeepcctns** [comment]
ok thanks..now its working.....
