### ISSUE TITLE
BSOD memory_management code day after installing

### ISSUE THREAD

**Issue by Movisivi** [namazso/SecureUxTheme#34]
On Windows 10 20H2

**Comment by Movisivi** [comment]
I uninstalled ultrauxthemepatcher and ran sfc/scannow (with some corrupted files idk) and memory diagnostics. No bsod since 2 hours ago. Hopefully that was it

**Comment by namazso** [comment]
MEMORY_MANAGEMENT bsods usually relate to failed memory, so you might want to check that.
Anyways, this cannot possibly cause that, worst this can do is crash winlogon, which will just throw you into login screen.
