### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by Ninjasr** [namazso/SecureUxTheme#38]
I wasn't completely sure if I should put this here, but it's probably very important.

I followed the steps on the wiki to install it. I checked settings, logonui and colors. Afterwards, I briefly switched to a theme and then back to default (or it might have been another theme that looked like default), then I clicked "reboot now" and my screen went black.

After a bit I tried Ctrl+Alt+Del and got an error. Then I reset the pc and the screen was still black. I reset it a few more times before entering recovery mode. I tried to start in safe mode but I got a blue screen. Afterwards, no matter what I did I'd get a reset, blue screen, recovery mode.

I tried to follow the login loop fix (after install) on the wiki but when I got to the registry, there were no keys there... only the last restore point (attempting to restore from it lead to a failure). I attempted to reset which lead to an error. Attempting to uninstall the last update also lead to a failure. Currently, I'm backing up my files and planning to reinstall windows.

I was on 1909 and I previously had UltraUx installed, I actually installed SecureUx right after I rebooted from uninstalling UltraUx. I also had MacType installed, although I'm not sure if that affected anything. The theme I switched to was for 1909 (the theme I may have switched to was also for 1909).

I'm not sure what I did and I'm scared of repeating it on my fresh install. Just wanted to report this, in case it's a bug or something y'know.

**Comment by namazso** [comment]
This thing isn't capable of causing blue screens, you have something more serious going on. Worst that can happen here is login loop.. I think, although I'm going to test corrupted install with LogonUI hook installed.

Also, why'd you enable both color rename and LogonUI? they do exactly the same and only one is enough.

**Comment by namazso** [comment]
Yeah just checked, deliberately corrupting with all the hooks doesn't cause blue screens, just a black empty screen as expected from a crashing LogonUI.

Sounds like you have some unrelated system corruption.

**Comment by Ninjasr** [comment]
Thought so, guess I messed up somewhere else.
