### ISSUE TITLE
How to install this and apply themes?

### ISSUE THREAD

**Issue by ilhamepri** [namazso/SecureUxTheme#4]
can you provide gif for installation? or just step by step

**Comment by namazso** [comment]
0. Download & start installer
1. Click Install
![image](https://user-images.githubusercontent.com/8676443/74597506-d80c7900-5060-11ea-982a-87507a6e02c6.png)
2. Reboot
3. Get a theme, throw its folder onto your desktop or something
4. Find the .msstyle files (*not* the theme files) in it
![image](https://user-images.githubusercontent.com/8676443/74597516-0be79e80-5061-11ea-8d1b-722ba5d7fb87.png)
5. Start installer again, go to install panel
6. Drag & drop the .msstyle files onto the window
![image](https://user-images.githubusercontent.com/8676443/74597528-2e79b780-5061-11ea-941c-9f63942674e5.png)
7. Move the .theme files and the folders next to them (if any) into `C:\Windows\Resources\Themes`, like this: 
![image](https://user-images.githubusercontent.com/8676443/74597502-ba3f1400-5060-11ea-80bf-b6f97596a9a5.png)
8. Click "Hooked personalization"
9. Click the theme to set it
![image](https://user-images.githubusercontent.com/8676443/74597534-46513b80-5061-11ea-8ace-ea37af500fe9.png)


To get a new theme later just do the steps from 3.

**Comment by namazso** [comment]
closing due to lack of interaction.
