### ISSUE TITLE
SecureUxTheme uninstalled after computer crash.

### ISSUE THREAD

**Issue by Azel04** [namazso/SecureUxTheme#40]

**Comment by namazso** [comment]
uhh.. ok?
any info or anything?
i hope you understand this isn't a too useful report like this

**Comment by Azel04** [comment]
oh sorry.

My computer crashed because of an unstable overclock on the GPU.

Windows version: 20H2
CPU: Ryzen 5 2600
GPU: Radeon RX Vega 56
Ram: 16GB
PSU: 650w 80+ bronze
SSD: Sabrent m.2 256gb.
HDD: 1x1TB and 1x3TB

**Comment by Azel04** [comment]
If there's a log of this program i'll send it, but I can't see any.

**Comment by namazso** [comment]
well, a description of what exactly you did (including install options, restarts, theme applies, etc..), when the "crash" happened, and what you mean by crash. 
If you mean BSOD then it's an unrelated problem, this thing is incapable of causing a BSOD.
Also, there is some log in bottom right of ThemeTool, but that's for diagnosing other class of errors, the injected dll is too barebones to implement real logging functionality.

**Comment by namazso** [comment]
oh wait, just saw this:

> My computer crashed because of an unstable overclock on the GPU.

so how is it related to SecureUxTheme then?

**Comment by Azel04** [comment]
Is it fine if I reinstall it?

Sorry if i bothered you. I'm new to this tool.

**Comment by namazso** [comment]
> Is it fine if I reinstall it?

probably. even if something goes wrong, there's recovery guides linked in readme.

And yeah, if you got a BSOD then it almost certainly has nothing to do with this software. If this would've caused some problems, you'd see a black screen or repeated logging in screen with working cursor.

**Comment by Azel04** [comment]
oh ok

Thanks for the info!

Bye!
