### ISSUE TITLE
Default app mode breaks themes

### ISSUE THREAD

**Issue by LuxVeris** [namazso/SecureUxTheme#41]
I'm not 100% sure if this is the correct place to put this, however on winver 1909 the "choose default app mode" breaks the colors on some themes when "dark" is selected.
![example](https://user-images.githubusercontent.com/77125882/103943683-7e8dbc80-5100-11eb-9c3b-64f50cd29847.png)

**Comment by namazso** [comment]
not the right place, sorry
whatever Microsoft or theme creators break i can do practically nothing about.
