### ISSUE TITLE
Bug: Black rectangles and ghost windows with patched themes since 21286 (Insider Preview - Dev channel)

### ISSUE THREAD

**Issue by enoversum** [namazso/SecureUxTheme#42]
Dear folks,

since last week’s Insider Preview from the Dev channel (21286), patched themes cause visual glitches on Windows. 
When you have a patched theme applied, especially UWP apps create black rectangles after closing, also when they auto-minimise (e.g. on startup) themselves. Also, certain apps and the new Update/system settings panel open, but appear as ghosts. You have to click 3-4x on the taskbar icon to actually make it visible.

This still happens with this week's new Insider Preview, and only with patched themes. If I apply a standard Windows theme, either through Windows settings or the ThemeTool, the issues go away. Graphics card drivers are not the issue, as it stays unaffected and only occurs through a patched theme application. Latest ThemeTool, with SystemSettings and LogonUI, but not the Explorer hooked.

**Comment by namazso** [comment]
i just confirmed this is a change in the theme structure. ask the theme developers to update their themes.

![image](https://user-images.githubusercontent.com/8676443/104649289-cd18f900-56b4-11eb-9eba-bf3c47e7f55e.png)

**Comment by enoversum** [comment]
@namazso Thanks, I just contacted the theme creator. Thanks for pointing out where the problem comes from.

**Comment by GavinRay97** [comment]
@namazso Sorry to be annoying -- but I have this issue as well, and I also use Insider Preview:

![image](https://user-images.githubusercontent.com/26604994/106173451-f0867e00-6161-11eb-9392-f305906b1064.png)

It didn't happen until recently.

My question is that I have one other issue which is more severe:

**The problem is that:**
- File-transfer dialogues "Copying File to... 98% completed", remain open after finishing, and I cannot close them. They are drawn over some other apps as well.
- There are a handful of other apps which have this behavior too. Can't close the window, they draw themselves over some of the application layers.

Only thing that fixes it is restarting `explorer.exe`.

---

Was curious if you might know whether the this issue is also related/the same as the one you discuss above?

**Comment by namazso** [comment]
@GavinRay97  If it goes away with default theme, it is almost certainly the same issue. They added completely new fields to that color structure so it's very well possible that it causes some troubles.

**Comment by enoversum** [comment]
@GavinRay97 As far as I understood @namazso this is due to a change in the structure of Windows themes in the Insider Previews, and the theme authors have to edit their themes. I have yet to see any theme to apply these changes. At least the ones I am watching have none. You could so far only revert back to the ugly Windows standard designs. @namazso if theme authors changed their themes to work with the new version provided by the Insider Previews, would they still work with normal Windows versions?

**Comment by namazso** [comment]
>  if theme authors changed their themes to work with the new version provided by the Insider Previews, would they still work with normal Windows versions?
probably. the additions you see at the end which probably cause these problems would definitely work. the changes earlier though.. not sure. But those even if broken would just produce some odd colors somewhere, nothing more.

**Comment by GavinRay97** [comment]
> As far as I understood... You could so far only revert back to the ugly Windows standard designs.
> And I have the same behaviour with explorer dialogues.

Ah, I feared as much 😭 

Compared to the alternative, I think I will live with super-broken and buggy Explorer windows + dialogues and `explorer.exe` restarts.

Some apps which integrate native Windows elements for their GUI (Win32 API I think) are utterly unbearable elsewise, and the difference is night + day in experience when using a nice theme.

Thanks so much for creating and maintaining this tool @namazso ^^

**Comment by enoversum** [comment]
> > if theme authors changed their themes to work with the new version provided by the Insider Previews, would they still work with normal Windows versions?
> 
> probably. the additions you see at the end which probably cause these problems would definitely work. the changes earlier though.. not sure. But those even if broken would just produce some odd colors somewhere, nothing more.

Ah, thanks, @namazso . It sounds as if Preview users are somewhat doomed until the actual change for normal Windows versions is gone through. Since I cannot edit themes myself, I fear we just have to wait. Thanks for clarifying those matters!

**Comment by enoversum** [comment]
> > As far as I understood... You could so far only revert back to the ugly Windows standard designs.
> > And I have the same behaviour with explorer dialogues.
> 
> Ah, I feared as much 😭
> 
> Compared to the alternative, I think I will live with super-broken and buggy Explorer windows + dialogues and `explorer.exe` restarts.
> 
> Some apps which integrate native Windows elements for their GUI (Win32 API I think) are utterly unbearable elsewise, and the difference is night + day in experience when using a nice theme.
> 
> Thanks so much for creating and maintaining this tool @namazso ^^

@GavinRay97 Wow, that's a swift move. I got really mad with those broken windows and dialogues, so for peace of mind I switched back to a more standard theme. There are still ways with Stardock Curtains to have at least parts of themes back. The true Dark Mode though is not possible anymore. Yes, it's night and day, I hadn't figured this before I had to painfully switch back.

**Comment by namazso** [comment]
Actually.. I might as well just tell you how to fix these themes yourself..

1. Install: Resource Hacker, HxD
2. Open the .msstyle in Resource Hacker
3. go to AMAP, save as BIN
4. open the resource in AMAP in HxD
5. go to the end and paste this:
```
20 4E 00 00 F1 00 00 00 49 01 00 00 66 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 58 00 00 00 58 00 00 00 10 00 00 00 38 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 10 27 00 00 00 00 80 3F 00 00 00 00 00 00 00 00 01 00 00 00 00 00 7A 44 00 00 00 00 02 00 00 00 05 00 00 00 00 00 00 00 64 00 00 00 02 00 00 00 00 00 80 3F 00 00 00 00 00 00 00 00 20 4E 00 00 F1 00 00 00 49 01 00 00 66 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 58 00 00 00 58 00 00 00 10 00 00 00 38 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 10 27 00 00 00 00 80 3F 00 00 00 00 00 00 00 00 01 00 00 00 00 00 7A 44 00 00 00 00 02 00 00 00 05 00 00 00 00 00 00 00 64 00 00 00 02 00 00 00 00 00 00 00 00 00 80 3F 00 00 00 00
```
6. it will ask you about changing filesize, it's ok
7. save
8. right click that AMAP resource
9. replace with the file you just edited

**Comment by GavinRay97** [comment]
@namazso 

Wow, so grateful for you to have share that info with us 🙏
How did you know to do this/where did you learn this wizardry? 👀

Just to double-check (I have no clue what I'm doing lol), did I do this right?

![patch-windows-theme](https://user-images.githubusercontent.com/26604994/106203872-0c9e1580-618a-11eb-96f0-27c3abf19e62.gif)

**Comment by namazso** [comment]
yeah, that should be it. did it work?

**Comment by enoversum** [comment]
@namazso What theme are you working on exactly? If you succeed, I'll be happy to use your files, so I don't have to fiddle with it. Looks like either BigSur or Nord theme by niivu.

**Comment by GavinRay97** [comment]
> yeah, that should be it. did it work?

Seems to still be bugged -- but it could just need a restart. Will report back in within a day or so to say for sure 👍 

Below attached GIF of some example behavior. If I try to close the window for this app directly, it becomes frozen on the desktop. (What you see is me trying to click the now-dysfunctional "close" buttons afterwards). It can be minimized no problems. Only way to prevent this, is to use the task-tray icon to right-click -> "Close application":

![bugged-window](https://user-images.githubusercontent.com/26604994/106218152-cb672f00-61a4-11eb-85c9-477296390ff5.gif)


> Looks like either BigSur or Nord theme by niivu.

Haha, nailed it -- it's Big Sur 2 by niivu

**Comment by GavinRay97** [comment]
Okay, following up on this (I won't give up so easily!):

I tried to repeat the above steps and patch + reapply a couple of times, just to make sure I was not doing anything wrong.

Still no luck. But, one thing I noticed, is that the hex series meant to be inserted at the end of the `AMAP.bin`, seems to already exist with some of the values slightly altered. And this series is repeated ~3 times at the end of the file:

![image](https://user-images.githubusercontent.com/26604994/106318053-3b28f880-623d-11eb-9e53-a1d676883f60.png)

I'm not sure what this hex does/is, but you can see a very similar string repeated twice above the `notepad.exe` containing the one I'm meant to add, and then once more below it until end-of-file.

I can see where this string is coming from. If I open `aero.msstyles` from official style, it's there:

![image](https://user-images.githubusercontent.com/26604994/106318342-d28e4b80-623d-11eb-90bb-b3fd063e5867.png)

This is as far as I've been able to get in my investigation 😅 

In the unlikely event anyone wants to poke at it, I've attached the (broken) patched + unpatched `AMAP.bin`, as well as the entire theme folder and resources in the zip below

[BigSur2-Theme-Patching-Progress-Resources.zip](https://github.com/namazso/SecureUxTheme/files/5895903/BigSur2-Theme-Patching-Progress-Resources.zip)

**Comment by GavinRay97** [comment]
@enoversum So I tried your suggestion and downloaded Stardock Curtains.

Not familiar with the way that Windows UI API's work, but this is what the Win32 bits of my DAW look like with the Curtains theme vs the `.msstyles` 😢 

Ah well, was worth a shot haha

![reaper-stardock](https://user-images.githubusercontent.com/26604994/106361986-59026600-62ee-11eb-8849-17c1c2b81595.png)

![reaper-patched-theme](https://user-images.githubusercontent.com/26604994/106361988-5b64c000-62ee-11eb-90cd-449eb5b6dea0.png)

**Comment by enoversum** [comment]
@GavinRay97 Yeah, it's not a 1:1 equivalent, I know, but it has at least a bit more excitement and non-standard style than just pure Windows. This is a way I can live for now, until themes are possible again the usual way. 
Too bad you did not have as much luck editing the theme files!

**Comment by GavinRay97** [comment]
I am leaving a comment for niivu on Deviant Art, sharing all this information. Maybe he understands this better.

Have also tried to Google for people talking about the patched theme issue introduced in 21286 build, but I think the community is just too niche/small to turn up anything =/

It's probably not worth your time versus the amount of engineering talent you have, but if you're interested, I would be willing to donate $20-30 for an update to my theme patch @namazso. Maybe @enoversum would chip in too?

Or if anyone can figure out what I did wrong, and spoonfeed me instructions -- I would be willing to write a script to automate patching themes + publish it publicly. (Or could incorporate it as a side-tool to SecureUxTheme for when people start complaining of this problem in some months when it hits stable release).

If not, also not a problem. I will cut my losses and go away + stop bothering you and spamming your issue comments 😅

**Comment by GavinRay97** [comment]
Okay, for posterity's sake, going to post a fix for @enoversum

By pure chance (my hard-drive was being fucky), I was having some perf issues, and so went looking for ways to improve Windows performance.

In the settings or start menu, go to "Adjust the appearance and performance of Windows":
![image](https://user-images.githubusercontent.com/26604994/107040477-43c58580-678d-11eb-8125-25fa6f3668ac.png)

And then from this window, I'm not entirely sure WHICH settings fix it, but the following works for me and I'm not messing with it any more 😂 It works now

![image](https://user-images.githubusercontent.com/26604994/107040616-77081480-678d-11eb-880a-7eeb3f4c9fe6.png)

Absolutely, under no circumstances, should you ever disable the box that says "Smooth edges of screen fonts". That's a piss-poor label for what it does. I initially went with "Best Performance" from the radio buttons at the top (which I assume is just all of these unchecked) -- after restarting, every font on every app was blurry + unreadable + jagged. I thought had really damaged something until I noticed that option in the menu and tried re-enabling it.

(That option should more aptly be named "Prevent all fonts from becoming unreadable.")

Okay, hopefully that's helpful, and happy Friday to you folks. Hope you enjoy your weekend =)

**Comment by enoversum** [comment]
@GavinRay97 Ah, I see - so you basically disabled _all_ of what there is on animation and effects on Windows, going naked, and by thus enabled yourself to use themes again :D . That is a really mind-bending way of handling it. 
Thanks in any way for your findings and posting it here. I'd believe I rather have a minimum of animation going on my systems and sacrifice the themes for now, than having the theme, but a very barebone interaction with my computer :) .

**Comment by GavinRay97** [comment]
Sure, no problem. It's maybe a case of a single one of those options fixing it too

(If I had to guess, maybe the option around animation for minimize + maximize, since this bug also happened when I would try minimize certain child-windows too -- they wouldn't minimize and would then become frozen ghost-screens)

But just figured I'd come full circle and leave a solution for future-searchers. Maybe someone else will do a calculated experiment for which toggle state(s) are required for non-breaking Theme functionality haha.

**Comment by enoversum** [comment]
> Sure, no problem. It's maybe a case of a single one of those options fixing it too
> 
> (If I had to guess, maybe the option around animation for minimize + maximize, since this bug also happened when I would try minimize certain child-windows too -- they wouldn't minimize and would then become frozen ghost-screens)
> 
> But just figured I'd come full circle and leave a solution for future-searchers. Maybe someone else will do a calculated experiment for which toggle state(s) are required for non-breaking Theme functionality haha.

Yes, I could imagine it has to do with minimising and maximising - the problem mostly happens with UWC and other windows minimising to the systray. Plus explorer. Let's hope this one is solving itself soon, so no needy workarounds to go with :)! Thanks again for your findings!

**Comment by CristianDragos** [comment]
Hey guys, I tried the fix above suggested by @namazso https://github.com/namazso/SecureUxTheme/issues/42#issuecomment-769254373 but as @GavinRay97 confirmed, it didn't work.
It definitely has something to do with the min/max visual effects which if disabled seems to be "fixing" the problem.
Any other ideas of how to fix this without disabling the min/max effects?
Thank you to everyone involved for helping out!

**Comment by enoversum** [comment]
Just coming back here to clarify: Even the current version of UltraUXThemePatcher, which states to be ready for the current Insider Preview builds, doesn't solve the problem, as @namazso pointed out. But you can easily only disable animation in Windows for windows, and the bug doesn't appear anymore. Not the sexiest way, but it works for now (so you don't need to disable all visual FX for Windows, phew). Happy weekend everyone.

**Comment by CristianDragos** [comment]
Hey guys, any updates on this? Did anyone manage to find a fix for the themes themselves without any system settings workaround?

**Comment by enoversum** [comment]
> Hey guys, any updates on this? Did anyone manage to find a fix for the themes themselves without any system settings workaround?

Hey @CristianDragos, unfortunately not. niivu states his themes are compatible with 21H1, but no matter which of his themes I test, they also have the animation bug leaving black rectangles etc. Just tried today. 
While animations on Windows in general are more or less neglectable to some extent, when you use multiple (virtual) desktops it kind of gets a bit distracting that you don't see the transition from one desktop to another. I would so much love for a solution as well :) .

**Comment by namazso** [comment]
@enoversum did you downgrade to 21H1 and it's also happening there too now?
I'm on 21H1 and my theme intended for 20H2 works just fine

**Comment by enoversum** [comment]
@namazso I'm on the latest Insider build, and I had believed it's 21H1 (21387.1)? I believe the new animations were introduced towards 21H1, so I'm wondering what could be the problem here…

**Comment by namazso** [comment]
@enoversum 21H1 is 19043.x
you're still on some insider version very far away from stable. 21H2 is believed to will be based on 20348.1 (at least latest Server 2022 preview identifies itself as 21H2 with that version)

**Comment by enoversum** [comment]
@namazso It is the next-to-latest Insider Preview for the regular Windows. As far as I've now read, it's the 21H2 pre-version, yet lacking any new features, so basically a 21H1. The build version number is going to be reverted to a lower number soon. Still not really getting what the problem is here with the Preview. No animations have been added, as far as I know, in the last months.

**Comment by CristianDragos** [comment]
@enoversum themes work fine one 21H1 stable release since it was mostly a minor update. The problem is in the upcoming 21H2 which brings a lot of changes in the UI.
@namazso did you test your themes on the latest insider preview version close to 21H2?

**Comment by namazso** [comment]
@CristianDragos I just tested it on that server preview i mentioned, seems to work just fine:
![image](https://user-images.githubusercontent.com/8676443/120367572-543bd600-c311-11eb-8037-8b170b8a5a9d.png)
theme is https://www.deviantart.com/kdr3w/art/Dark-845402016

**Comment by CristianDragos** [comment]
@namazso Sounds like good news! Hopefully, this will stay true in the final Fall release 21H2 as well. Thanks for the confirmation!

**Comment by enoversum** [comment]
@namazso Just for the sake of completeness - the typical problems with themes were (and in my case are) ghost windows when using UWP apps, and Windows settings needing three clicks on the app icon in the task bar to actually appear as a window. Can you confirm with your current theme that these glitches don't happen anymore?

**Comment by namazso** [comment]
@enoversum I think it looks fine:

https://user-images.githubusercontent.com/8676443/120373810-1642b000-c319-11eb-953f-61bd58745603.mp4

**Comment by enoversum** [comment]
@namazso Indeed, that looks absolutely smooth. I so much would love to solve this. Thanks for confirming this must be a problem with the future builds. Too bad.

**Comment by Samuel-B-D** [comment]
A few other things seems to be changed too. The theme I was using on Windows 10 20H2 still mostly work (Toxic by Mr.GRIM), but in addition to the problems mentionned above (ghost windows and maximizing windows filling only the top-left quarter of the screen with the other 3 quadrant being stretched messes), the window decorations are not being applied properly.

The buttons are shown properly, but the title bar and borders are the flat color of the theme's color instead of using the proper decoration. This is probably due to the changes made for the rounded corner. However, since these rounded corners are not applied when gpu driver is not installed, maybe there is a registry key somewhere to disable these? Or it might even be in those new fields added to msstyle's format?
