### ISSUE TITLE
Can't build SecureUxTheme - SecureUxTheme.dll is not a valid Win32 application

### ISSUE THREAD

**Issue by MicrogamerCz** [namazso/SecureUxTheme#44]
I want to install SecureUxTheme (because UltraUXThemePatcher is not working), but I have problem with building it. I have every time "Can't run \SecureUxTheme-master\bin\Release\Win32\SecureUxTheme.dll, it's not a valid Win32 application". I have the same problem with x64 and ARM64 and Win32 on ThemeTool.

(why this can't have simple installer without troublesome Visual Studio Solutions)

**Comment by namazso** [comment]
> why this can't have simple installer without troublesome Visual Studio Solutions

what do you mean? that's what releases are for. why else would you download the source code if you don't want tk do this?

As for why your build isn't working: follow the building guide, sounds like you built in incorrect order.

**Comment by ItsProfessional** [comment]
I know I'm late but this is the only issue about this. You are clicking the run button on the toolbar. It is running the SecureUxTheme project but default, which is a dll and not an exe so it says that error that it is not a win32 program. You have to right click on themetool and expand debug and select start without debugging to run the ThemeTool. I'm sure there's a way to change the default project to ThemeTool, and I'll add it here if I find out.
