### ISSUE TITLE
I cant download the setup

### ISSUE THREAD

**Issue by sushigamer666** [namazso/SecureUxTheme#45]

**Comment by namazso** [comment]
what can't you?

**Comment by sushigamer666** [comment]
> what can't you?

bcs i click on latest realease and downloads the theme tool

**Comment by namazso** [comment]
that **is** the installer

**Comment by sushigamer666** [comment]
but says that i need yhe installer to continue

**Comment by namazso** [comment]
what says this where?
have you tried following the [step by step guide](https://github.com/namazso/SecureUxTheme/wiki/Help:-Step-by-step-installing-SecureUxTheme-and-a-custom-theme) on the wiki?

**Comment by sushigamer666** [comment]
> what says this where?
> have you tried following the [step by step guide](https://github.com/namazso/SecureUxTheme/wiki/Help:-Step-by-step-installing-SecureUxTheme-and-a-custom-theme) on the wiki?

i didint run as administrator at first time 😅
