### ISSUE TITLE
every app from windows start menu or  statusbar will open minimize

### ISSUE THREAD

**Issue by geowolf1000** [namazso/SecureUxTheme#46]
hi,
i am insider dev project user 
curently on Windows 10 Insider Preview Build 21318
and use your latest 
all apps from start menu will open minimize have to double click to open window...
also have artifacts from background notification menu
three dots hide/ show very quick

**Comment by namazso** [comment]
does this happen on default theme?

**Comment by geowolf1000** [comment]
No
definitely no

**Comment by geowolf1000** [comment]
fixit 
change advance settings (perfomance) and disable visual effect to custom with tic only shadows under mouse
this fix both problem
