### ISSUE TITLE
Does not load (not loaded)

### ISSUE THREAD

**Issue by eshsdhsd** [namazso/SecureUxTheme#47]
After install and restart it is not loaded. How to do this, give some instructions

**Comment by namazso** [comment]
could be antivirus or pretty much anything interfering. post log (bottom right) and "modules" tab from process hacker.

**Comment by eshsdhsd** [comment]
1614877673572 > Version v2.1.2
1614877673572 > Running on 10.0.14393 flavor F
1614877673572 > MainDialog: is_elevated 0
1614877673572 > Session user: User Process user: User
1614877673576 > UpdatePatcherState: file_has_content 0 file_is_same 0 file_error 5 is_loaded 0
1614877823324 > SelectTheme: pTheme->GetVisualStyle failed with 80070490
1614881954774 > CurrentSelection: count is 0, expected 1

**Comment by namazso** [comment]
that's a new one. Do you maybe use some sort of antivirus besides defender? it seems like opening the patcher file (system32\SecureUxTheme.dll) results in ERROR_ACCESS_DENIED which really should never happen.
could you also check if the file is really there, and if yes what are the ACLs?
 a log output when trying to install (and running as admin) would be useful too

**Comment by eshsdhsd** [comment]
I don't know whats an acl and how to log an input,

**Comment by eshsdhsd** [comment]
Update got the file permissions here

[https://ufile.io/dch3ul4r](url)

**Comment by TreeBKO** [comment]
I have that problem too. But I don't have an antivirus. The dll file is there. what is a Acl? hereis my log
1669538188740 > Version v2.1.2
1669538188744 > Running on 10.0.10586 flavor F
1669538188745 > MainDialog: is_elevated 1
1669538188745 > Session user: admin Process user: admin
1669538188764 > UpdatePatcherState: file_has_content 1 file_is_same 1 file_error 0 is_loaded 0
1669538195603 > ApplyTheme(15)
1669538195604 > PatchThemeInternal(15)
1669538201194 > ApplyTheme: SetCurrentTheme returned 00000000

Any help will be appreciated
