### ISSUE TITLE
applications do not start

### ISSUE THREAD

**Issue by qzmtch** [namazso/SecureUxTheme#49]
hello, the problem is that after patching with such [settings](https://i.imgur.com/arpjqln.png), and restarting the computer, SolveigMMVideoSplitter program stops starting, perhaps other programs also do not start, checked 2 times in a virtual machine, after I could not detect the problem on the main pc, it turned out it's all because of the patcher
PS with UltraUXThemePatcher there is no such problem

**Comment by namazso** [comment]
Works on my machine. Possibly a theme issue, outdated themes can cause weird stuff

![image](https://github.com/namazso/SecureUxTheme/assets/8676443/dd88431c-cb64-4b6f-ab5a-770f4a7cbf59)
