### ISSUE TITLE
Slow log out/shutdown

### ISSUE THREAD

**Issue by TurboSlayer** [namazso/SecureUxTheme#5]
Ever since I started using SecureUXTheme, whenever I shutdown or log out I have to wait for a few seconds. So like when I do Win+L, I have to wait for like 2 seconds before the lock screen shows up. Or when I shutdown, I have to wait for a few seconds before the shutting down screen shows up.
Before I started using this, it was almost instant.

Any help would be appreciated.

**Comment by namazso** [comment]
Can you test without LogonUI fix? 
Since I use a debug feature to load it could cause some lowered performance on affected processes. This isn't really a problem on winlogon (the process in which patching must be done) since it mostly does nothing, but there's a possibility LogonUI does more processing making the effects visible. Regardless I'll look into if I can disable the debug features.

**Comment by TurboSlayer** [comment]
> Can you test without LogonUI fix?
Yep, it's back to normal now. It would be great though if you could find a way to have the LogonUI fix without changing the logout speed.

**Comment by namazso** [comment]
After further inspection it seems like the main performance penalty isn't from the runtime  (that being said, I'll disable some runtime stuff app verifier does in the next release), but from the application verifier's initialization itself, at least on my machine. This loads before SecureUxTheme,  and there are no options to disable it, or their hooks. On my severily resource limited VM lockscreen without SecureUxTheme took 0.716 seconds to appear with background, while 1.200 seconds with SecureUxTheme. I don't consider 0.484 seconds a dealbreaker.

If it really is for you, I can only recommend disabling LogonUI fix, then backing up and deleting *HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\DefaultColors* for fixing colors instead. I'll also consider moving this into an option in the installer

**Comment by TurboSlayer** [comment]
That's fine, I don't get the Task Manager theme issue anyway. Dunno if this is because the value for DefaultColors was not set, or if I'm just lucky. I enabled Logon UI fix just in case. Anyway thanks for your help 🙂.

**Comment by namazso** [comment]
> I don't get the Task Manager theme issue anyway

this is a thing for dark themes in general. if all of this is true:
* have a more recent windows 10 build (1803+ I think?)
* have the DefaultColors key set (this is the default)
* have a dark theme
* don't have the fix enabled
then when locking all programs will "forget" the background color and turn white next redraw. If any of these isn't true you don't even need the fix. Overall the registry changing way might be better anyways, so I'll consider changing the checkbox to do that instead.

> Anyway thanks for your help 🙂.
np
