### ISSUE TITLE
System does not restart

### ISSUE THREAD

**Issue by xhollycowx** [namazso/SecureUxTheme#50]
Dear all, 

For a year I have been using Ultimate Ux Themes to apply mods to my pc. When the Windows 20H2 updates were automatically installed, my mods disappeared and no longer showed. I decided to install SecureUxTheme without removing any of the previous mods.
I downloaded SecureUxTheme and installed (no theme yet applied, only software installed). Then I rebooted the pc, in order to finish the installation. However, my windows would not load any more. I just get a black screen which does not allow me to do anything. I can however access bios.
I tried the solution at "Q: Help, SecureUxTheme broke my install and it's login looping now", however, the keys that are mentioned here are not present in my system.

My next step/solution would be to delete the .dll file.
Is it possible to delete the .dll file from cmd, or would this cause further problems?
Do you have other suggestions for me to resolve this situation?

With kind regards,

**Comment by namazso** [comment]
> Is it possible to delete the .dll file from cmd, or would this cause further problems?

well, it wouldn't cause any more problems, but it certainly wouldn't solve any either. for the quick tutorial gif I did exactly that to cause the issue.


> the keys that are mentioned here are not present in my system.

are you *very* sure of this? did you mount the actual registry, and not just trying to find the keys in windows Recovery Environment's registry? without those keys SecureUxTheme never loads, thus does absolutely nothing at all.

**Comment by namazso** [comment]
closed due to lack of activity
