### ISSUE TITLE
Explorer restarts every  5 seconds

### ISSUE THREAD

**Issue by Lubzz** [namazso/SecureUxTheme#51]
I installed SecureUxTheme, and then after i rebooted, explorer restarted every 5 seconds.. i tried alot of solutions online, and i even rebooted it like 5 times. and i cant uninstall SecureUxTheme either because i need to run it as admin and when i right click it needs to load a bit. while its loading, explorer restarts. so i cant open it as admin and cant uninstall it. Please help

**Comment by namazso** [comment]
follow the uninstall guide from the faq: https://github.com/namazso/SecureUxTheme/wiki/Help:-Login-loop-after-installing-SecureUxTheme

also, just don't install explorer hook then. You can still set themes from the program itself, or just upgrade to windows 10 so you can use settings hook with settings to set themes.

**Comment by Lubzz** [comment]
> follow the uninstall guide from the faq: https://github.com/namazso/SecureUxTheme/wiki/Help:-Login-loop-after-installing-SecureUxTheme
> 
> also, just don't install explorer hook then. You can still set themes from the program itself, or just upgrade to windows 10 so you can use settings hook with settings to set themes.

okay thanks.. ill try that

**Comment by lordcyb3r** [comment]
just thought i would jump in with a niffty tip. get yourself a windows PE recovery iso and throw it on a flashdrive. Its a good nuclear option for when things break so bad that safemode wont even save you. it just gives you a little one time boot windows environment with drive access so you can move/replace things as needed.
