### ISSUE TITLE
My main goal is to get the generated titlebar colors for Windows 8, do I need to use "Hook explorer", or "Hook system Settings"?

### ISSUE THREAD

**Issue by mzso** [namazso/SecureUxTheme#53]
Hi!

My main issue with Window 10 is the ugly titlebar colors it generates from the bakckground image.
So there's this one Windows 8 theme that I found: https://www.deviantart.com/sagorpirbd/art/Windows-8-Themes-for-Win10-Final-556761647

I installed it with this tool (With ignore background/sound, so it wouldn't mess up my customizations).
But by default it has a static color, and when I enable "Automatically pick an accent color from my background" in the color settings, the ugly Windows 10 colors are generated instead of the colors the Windows 8 theme would generate.

Would "Hook explorer", or "Hook system Settings" help with this?
Is it even possible?

I've spent to much effort to get good looking colors generated. I hoped at last installing the Win8 the theme would work.

**Comment by mzso** [comment]
Well, I tried it. It only made explorer/settings slower. :(
The Windows 10 ugly colors came back.

Anything else I can do/try to get the Win 8 colors to work with slideshow background images?

**Comment by namazso** [comment]
> Anything else I can do/try to get the Win 8 colors to work with slideshow background images?
no idea, this is a theme thing, try asking people who make themes

the explorer/systemsettings hooks only allow you to set themes from those things (Personalization or Themes, respectively) and don't do anything else that'd change appearence
