### ISSUE TITLE
Won't let me apply theme

### ISSUE THREAD

**Issue by Iunyavii** [namazso/SecureUxTheme#54]
![image](https://user-images.githubusercontent.com/83040446/115787666-90822b00-a390-11eb-9ba8-1fef3f2c4029.png)
uhh been trying to apply this for a while. rebooted my laptop a bunch, but nothing seems to really work?? don't really know what else i can do.

**Comment by namazso** [comment]
are you sure you installed the themes correctly? see:
https://github.com/namazso/SecureUxTheme#q-selecttheme-ptheme-getvisualstyle-failed-with-80070002

**Comment by namazso** [comment]
closed due to lack of activity
