### ISSUE TITLE
Theme not applied to ribbon (Dunno whether it's the theme error or SecureUxTheme error)

### ISSUE THREAD

**Issue by KaitouStn** [namazso/SecureUxTheme#55]
![explorer_S89468EG7t](https://user-images.githubusercontent.com/46869376/117399938-41ef9780-af1f-11eb-82cc-f06783db20d7.png)

**Comment by KaitouStn** [comment]
Using Windows 20H2

**Comment by namazso** [comment]
This is normal, themes don't apply to ribbon. This is why everyone uses OldNewExplorer to get rid of the ribbon
