### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by lokize** [namazso/SecureUxTheme#56]
I first thanks for this software is very useful, i have a problem with permission denied even when I run as an administrator, i cant install any themes... 
![image](https://user-images.githubusercontent.com/19701630/117425342-18bc1080-aef9-11eb-9f8e-6bdfe381a7bb.png)

**Comment by namazso** [comment]
that's a weird one. just use Hook LogonUI instead of Rename DefaultColors. They achieve the same thing, the hook is just less performant

**Comment by lokize** [comment]
it didn't work, I just saw that maybe my build is not supported 10.0.21354, sorry!

**Comment by namazso** [comment]
Oh, i see you're on an insider version. Yeah they aren't tested, although usually it's just themes that break and not the tool itself. Maybe I'll look into it, but it's not priority, i prefer to check them when RTM comes out to MVS, that's usually a few weeks before general availability.

**Comment by namazso** [comment]
Supposedly last Windows 10 branch release is Server 2022 which is on a 20xxx version and works just fine so this is now irrelevant. Follow #60 for Windows 11
