### ISSUE TITLE
Disconnected by VAC: You cannot play on secure servers

### ISSUE THREAD

**Issue by MrFlitch** [namazso/SecureUxTheme#57]
Running this tool hooked causes a "Disconnected by VAC: You cannot play on secure servers". Uninstalling fixes the issue.
https://support.steampowered.com/kb_article.php?ref=2117-ILZV-2837.

**Comment by namazso** [comment]
interesting. Which hooks did you have enabled? neither can inject into the game so if this really is reproducible it's most likely an oversight on valve's part

**Comment by nodgear** [comment]
Playing cs and other valve games, i don't have this issue.

**Comment by namazso** [comment]
can't reproduce on default settings.
