### ISSUE TITLE
Turning off license dialog box? 

### ISSUE THREAD

**Issue by dreadbalaur** [namazso/SecureUxTheme#58]
Not exactly a bug, but I feel like there should be a way to turn off the license check dialog box permanently. Sure, it's good to make sure that users have read the license text, but, if I had already read it multiple times, I would prefer to not have to go through the dialog again whenever I open it.

**Comment by namazso** [comment]
I'll see what I can do about it, as the warranty & liability disclaimer the only thing people actually need to see, the rest are additional rights granted.

I was thinking about a more wizard-like UI for a while as it seems like using the current one is not intuitive enough for meny

**Comment by namazso** [comment]
I changed it to be only a single message box with only an OK button:

![image](https://user-images.githubusercontent.com/8676443/131200628-7c1a66f6-fd18-49d8-97a1-65d28a3c1c52.png)

Still pops up every time, might change that later.

**Comment by dreadbalaur** [comment]
After a few years is it reasonable to ask for a way to turn off the warranty disclaimer box too? This does not need to be worked into the main release.
