### ISSUE TITLE
Question about hibernation and fast start up

### ISSUE THREAD

**Issue by Drushgakyn** [namazso/SecureUxTheme#59]
Hello !
As the title say, I have a question about hibernation and the fast start feature in windows.
I have seen (on other ux theme patcher forums) that it is recommended, well maybe quite necessary to turn off these two features when using custom themes.
But with SecureUx, should I turn them off too? Because I really like the when the pc is booting fast...
Will there be a weird problem if I use SecureUx alongside these features?

Thanks in advance for your reply.
I don't know if it is the right place to ask questions though....

**Comment by namazso** [comment]
i don't see any reason they would be needed to be turned off.
