### ISSUE TITLE
Is it possible to change color of choosing folders in explorer in night mode?

### ISSUE THREAD

**Issue by Greenorine** [namazso/SecureUxTheme#61]
All my night themes picks blue highlight. Is it possible to change this thing?
![image](https://user-images.githubusercontent.com/41028671/123880425-12c43800-d95c-11eb-8705-7c57da1b1e85.png)
![image](https://user-images.githubusercontent.com/41028671/123880436-18218280-d95c-11eb-9e63-d42d50a757f1.png)

**Comment by dreadbalaur** [comment]
I doubt that it's caused by SecureUXTheme. It's either (a) all your themes use the blue highlight or (b) you forgot to hook something (maybe LogonUI?) in the installation tab. 
![test](https://user-images.githubusercontent.com/78159129/124842909-e7d67700-df4d-11eb-84ab-9df18db3eb2c.jpg)

**Comment by illnesse** [comment]
> ![test](https://user-images.githubusercontent.com/78159129/124842909-e7d67700-df4d-11eb-84ab-9df18db3eb2c.jpg)

I like those icons a lot, what are they called?

**Comment by dreadbalaur** [comment]
> I like those icons a lot, what are they called?
They are part of [niivu's Fluent Keys Icon set](https://www.deviantart.com/niivu/art/Fluent-Keys-Icon-Theme-860328216), which used [Tabler Icons](https://tablericons.com/) as the base.

**Comment by namazso** [comment]
Theme issue.
