### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by OmarShadowSpike** [namazso/SecureUxTheme#62]
I'm on windows 8.1, I have downloaded the file "ThemeTool.exe" I opened it but there's a message pop-up, It says "This app can't run on your PC" I don't know what's the problem. Is the problem because it isn't compatible in my pc? or others please help!

**Comment by namazso** [comment]
make sure your windows is up to date because it works for me:
![image](https://user-images.githubusercontent.com/8676443/126061757-dd3fefaa-de82-47de-a0f0-c3766febd9a3.png)

Are you sure there isn't some antivirus or something interfering, corrupting the file?
