### ISSUE TITLE
Theme not working on control panel

### ISSUE THREAD

**Issue by falcon646** [namazso/SecureUxTheme#67]
Not sure if this is an issue ith Secureux or the Theme itself. But when ever I apply  a dark theme for some strange reason the side panel on the conrol panel always remains white. No matter whichever dark theme i apply.
Attaching screenshot
The pic below is from Demo Night thme by niivu
![Capture](https://user-images.githubusercontent.com/35376307/129606800-9ab2f05b-149d-4a5f-a6a1-97b348310481.PNG)

Little Backstrory: I was on version 2004 before this and was using the same theme((As far as i remeber I didnt see this issue at that time) until my pc started slowing down. I decieded to do a fresh install of windows and this is wehn i started seeing this issue . I am currently on build versio 2004 build 19041.1165

**Comment by namazso** [comment]
it's a microsoft issue and i can't do much about it. you could maybe ask OldNewExplorer developer for a fix as it already contains some shell fixes
