### ISSUE TITLE
Questions :trl:

### ISSUE THREAD

**Issue by DESKTOPGOOOSE** [namazso/SecureUxTheme#68]
Yes, I know this is an extremely stupid thing lmao but whatever.

Is this compatible with Fast Boot and does this require a reboot? (im not a big fan of rebooting for whatever reason)

**Comment by namazso** [comment]
> Is this compatible with Fast Boot

Yes

> does this require a reboot?

Installing does, yes. Well, technically it will work without reboot on sessions created after install (so like if you RDP in it will already work without reboot, but I assume you don't care about this much)

**Comment by DESKTOPGOOOSE** [comment]
Yeah, all I just want is a custom theme.

**Comment by DESKTOPGOOOSE** [comment]
Is it also recommended to turn off the antivirus? (I use avast trl)

**Comment by namazso** [comment]
no (or at most for the length of the install), but after the install I'd recommend adding system32\SecureUxTheme.dll as if the antivirus ever deletes that file your install will no longer boot and you'll need to do the recovery guide in faqs

**Comment by namazso** [comment]
assuming this is answered. you can still comment on a closed issue anyways
