### ISSUE TITLE
Clicking Hooked Personalization does nothing

### ISSUE THREAD

**Issue by kalehead** [namazso/SecureUxTheme#7]
I've followed the tutorial in the wiki, I've uninstalled and reinstalled several times, done countless reboots, and even after all that, clicking Hooked Personalization still doesn't do anything. If I click it, the installer hangs for about half a minute, after which I can interact with it again, but nothing else happens.

![image](https://user-images.githubusercontent.com/7550178/77526961-108b4800-6e94-11ea-976e-a5dc25873923.png)

This is on a practically fresh install, with no other theme stuff installed (only a couple registry tweaks for the file explorer). Any ideas? I'm using Win10 LTSC 1809 x64

**Comment by namazso** [comment]
Win10 LTSC 1809 x64 was literally one of the test VMs, so this is quite weird. Can you post your explorer tweaks? that button works via installing the hook temporarily for explorer, then uninstalling it soon after, so might very well be related to that.

**Comment by namazso** [comment]
Also, could you check what happens if you enter `shell:::{ED834ED6-4B5A-4bfe-8F11-A626DCB6A921}` into the address bar of an explorer window?

**Comment by kalehead** [comment]
Thanks for the response!
> 
> 
> Win10 LTSC 1809 x64 was literally one of the test VMs, so this is quite weird. Can you post your explorer tweaks? that button works via installing the hook temporarily for explorer, then uninstalling it soon after, so might very well be related to that.

From what I recall:

- Installed OldNewExplorer
- Removed Dropbox and Network from the navigation pane
- Minor tweaks in WinAero Tweaker (different font, no shortcut arrows, a few other small changes)



> 
> 
> Also, could you check what happens if you enter `shell:::{ED834ED6-4B5A-4bfe-8F11-A626DCB6A921}` into the address bar of an explorer window?

![image](https://user-images.githubusercontent.com/7550178/77544122-47238b80-6eb1-11ea-87fd-7d52396091eb.png)

Classic personalization pops up.

Could OldNewExplorer be the issue? Forgot about that while opening the issue.

**Comment by namazso** [comment]
I tested with OldNewExplorer, it should work (although feel free to try without, can't hurt).
What I'm more interested about is your WinAero Tweaker changes - I suspect some conflicting injections or hooks, but couldn't reproduce it by setting random stuff.

**Comment by lolol1290** [comment]
Hello namazso
I used nebula theme from devianart
With your SecureUxTheme and followed the instruction from here
https://github.com/namazso/SecureUxTheme/wiki/Help:-Step-by-step-installing-SecureUxTheme-and-a-custom-theme

But, when I use Excel or Word
It looks like this (Screenshot below)
Is there any fix for this issue ?

![image](https://user-images.githubusercontent.com/51122994/77606906-5c4cf880-6f4b-11ea-9c51-43ffebc9dbca.png)

**Comment by namazso** [comment]
@lolol1290 next time please open a new issue

individual programs mishandling visual styles is out of the scope for this project (for a matter of fact, I did start researching for a way to handle themes per-process, but if I ever find a safe-ish way it will be a sepaeate program). You can try to get help on the theme's site, or customizing communities, but this is not a problem with SecureUxTheme (consequently, all other theme patchers suffer the same problem)

**Comment by lolol1290** [comment]
> @lolol1290 next time please open a new issue
> 
> individual programs mishandling visual styles is out of the scope for this project (for a matter of fact, I did start researching for a way to handle themes per-process, but if I ever find a safe-ish way it will be a sepaeate program). You can try to get help on the theme's site, or customizing communities, but this is not a problem with SecureUxTheme (consequently, all other theme patchers suffer the same problem)

Alright, thank you for the answer

**Comment by kalehead** [comment]
> 
> 
> I tested with OldNewExplorer, it should work (although feel free to try without, can't hurt).
> What I'm more interested about is your WinAero Tweaker changes - I suspect some conflicting injections or hooks, but couldn't reproduce it by setting random stuff.

Removing OldNewExplorer didn't fix it, so I doubt it's the issue. I've changed the following tweaks in WinAero:
![WinaeroTweaker_iVLReDLm1p](https://user-images.githubusercontent.com/7550178/77643342-da1efd00-6f67-11ea-8e71-a7ffa8726df1.png)
I don't see why any of these would be conflicting with SecureUxTheme. I tried disabling the Theme Behavior tweaks and restarting, but even that didn't change anything. Is there any built in logging feature in SecureUxTheme that I could use?

**Comment by namazso** [comment]
I wasn't successful in reproducing that yet, however you could try using this tool that (besides not being exactly ready for release yet) should work for now:
[Release.zip](https://github.com/namazso/SecureUxTheme/files/4396135/Release.zip)
please do not try checking the checkboxes on a real machine, i have no idea what some of the flags do.

**Comment by kalehead** [comment]
ThemeTool works perfectly! Problem solved, thanks for all the help 👍
