### ISSUE TITLE
Taskbar display looks bugged

### ISSUE THREAD

**Issue by ItsRize** [namazso/SecureUxTheme#70]
here is an image https://i.redd.it/kqz30f7i5ki71.png
There is a line between the start button and the volume and network icons are messed up

**Comment by namazso** [comment]
Is this Windows 8.1 or later?
Can you post log and link to theme? Most likely it's a version mismatch or a theme problem

**Comment by ItsRize** [comment]
> Is this Windows 8.1 or later?
> Can you post log and link to theme? Most likely it's a version mismatch or a theme problem

It is windows 10 the theme is Aero 7 https://www.deviantart.com/sagorpirbd/art/Aero-7-Themes-for-Win10-Final-523979941
It worked fine with ultraUXthemepatcher

**Comment by namazso** [comment]
please write your exact windows version (the one that winver displays)

**Comment by ItsRize** [comment]
21H1

**Comment by namazso** [comment]
can't reproduce.

UltraUXThemePatcher:

![image](https://user-images.githubusercontent.com/8676443/130342299-f05cc1ae-49c3-4c11-afe4-6a9fb92de577.png)

SecureUXTheme:

![image](https://user-images.githubusercontent.com/8676443/130342353-266398de-9dda-4e91-8548-e8f7d47309b3.png)

**Comment by ItsRize** [comment]
Oh, Well shit I think It is just my PC that has the issue, but thank you anyway

**Comment by namazso** [comment]
Your screenshot in the other issue shows that you have the ignore options checked.
I hope you didn't try doing that when applying this theme, as those options, as they say, ignore certain aspects of the theme being applied, which might interfere with how themes do things.

**Comment by ItsRize** [comment]
I tried first with them un checked then with them checked still nothing

**Comment by ItsRize** [comment]
I tried first with them un checked then with them checked still nothing

**Comment by namazso** [comment]
your (duplicate) mail reply exposed an unsubscribe authorization so i deleted that.

> I tried first with them un checked then with them checked still nothing

I don't know what could possibly be wrong in that case then. Try following this guide exactly, from scratch: https://github.com/namazso/SecureUxTheme/wiki/Help:-Step-by-step-installing-SecureUxTheme-and-a-custom-theme
as this is exactly what i went through on the VM.

**Comment by ItsRize** [comment]
I think I know the reason.
When I did this I watched a youtube video on how to make windows 10 like 7 they used a program to change the icons of the volume and ethernet icons I did the the same but the theme screwed those icons up for me but for them it didn’t idk why

**Comment by ItsRize** [comment]
> your (duplicate) mail reply exposed an unsubscribe authorization link so i deleted that.
> 
> > I tried first with them un checked then with them checked still nothing
> 
> I don't know what could possibly be wrong in that case then. Try following this guide exactly, from scratch: https://github.com/namazso/SecureUxTheme/wiki/Help:-Step-by-step-installing-SecureUxTheme-and-a-custom-theme
> as this is exactly what i went through on the VM.

I fixed it It was an activation issue I activated the VM using PowerShell them changed the default windows mode in PC settings to Dark and now It works
