### ISSUE TITLE
After recent updates, I can no longer type in the windows start menu without clicking into the search bar.

### ISSUE THREAD

**Issue by NANDMusic** [namazso/SecureUxTheme#71]
Tried multiple themes, and powershell fixes.

Not a deal breaker but is rather annoying.

Windows 10 Version 21H1 19043.1165

**Comment by NANDMusic** [comment]
After uninstalling update KB5005033, the issue is resolved.

**Comment by namazso** [comment]
Can't reproduce. Can you link a theme that caused this for you?

**Comment by NANDMusic** [comment]
I tried Penumbra 10 and BIB3 on Deviantart.

There have been reports of some users ALT+ TAB shortcut breaking as well after this update as well, which is interesting. Might be irrelevant but figured I would mention it.

**Comment by namazso** [comment]
https://user-images.githubusercontent.com/8676443/130345275-1777bbbe-a02c-4559-b1c8-37d99103c227.mp4

Seems to work here. are you sure it's not some shell extension or other customization utility messing it up?

**Comment by NANDMusic** [comment]
> 
> qdghOKuqEU.mp4
> 
> Seems to work here. are you sure it's not some shell extension or other customization utility messing it up?

Solved. It was caused by the update, however it was fixed by setting taskbar to bottom, then disabling News & Weather on the taskbar.
