### ISSUE TITLE
SecureUxTheme doesn't change all the window themes

### ISSUE THREAD

**Issue by RandomPenguin1778** [namazso/SecureUxTheme#72]
Hi,
i am a user of this tool . the themes work successfully on the system applications but not most of them (for eg : MS store, Settings etc . . . this mostly happens to UWP applications) so please fix this issue ASAP .

**Comment by RandomPenguin1778** [comment]
(Update : Only some applications work with these themes . most of them don't work)

**Comment by namazso** [comment]
these apps draw their own caption, ignoring the theme. 
this is a per-app problem, hence out of scope for this project
