### ISSUE TITLE
Always add secureuxtheme.dll as an exception

### ISSUE THREAD

**Issue by ItsRize** [namazso/SecureUxTheme#76]
While my antivirus (bitdefender) doesn't detect it I still add the file as an exception so It never interacts with it or scans it basically this makes the file invisible to your AV when Installing tell it you will reboot later then go into your AV and add an exception C:\Windows\system32\SecureUxTheme.dll

Not an Issue Just something people should know also I tested it on 21H2 and it works like normal

**Comment by namazso** [comment]
this is implicitly mentioned in the readme: https://github.com/namazso/SecureUxTheme#garbage-antiviruses maybe i should make it more explicit

**Comment by ItsRize** [comment]
> this is implicitly mentioned in the readme: https://github.com/namazso/SecureUxTheme#garbage-antiviruses maybe i should make it more explicit

yeah probably
