### ISSUE TITLE
theme broke after sleep  

### ISSUE THREAD

**Issue by tjhecker** [namazso/SecureUxTheme#77]
theme doesn't work I put my laptop in sleep and I wake up the theme doesn't works please fix it.

**Comment by namazso** [comment]
Enable LogonUI hook (and click install after), probably renaming DefaultColors failed for whatever reason. If it still persists, post the following:
- exact OS version from winver
- log of installing
- theme used
- screenshot of themes folder

**Comment by namazso** [comment]
closed due to lack of response
