### ISSUE TITLE
Windows Logon Screen Black Cannot Access Windows

### ISSUE THREAD

**Issue by jameel-ansari** [namazso/SecureUxTheme#80]
After clicking "Install" and rebooting, I can't reboot to the Windows login screen. My login screen is black.

I have booted to recovery and follow the instructions in this post:
https://github.com/namazso/SecureUxTheme/wiki/Help:-Login-loop-after-installing-SecureUxTheme

But it didn't work. I deleted the winlogon.exe FOLDER as you did in the gif. But I did not have explorer.exe, LogonUI.exe or dwm.exe folders. And VerifierDLLs and GlobalFlag were not present inside Systemsettings.exe.

I also tried:
- System restore point
- Deleting the SecureUxTheme.dll from %windir%/system32 via cmd prompt
- Booting into safe mode
- Plugging/unplugging laptop into monitor
- Automatic start-up repair

Nothing has worked. I am stuck I cannot access my laptop.

**Comment by Jameel10100** [comment]
I closed this thread by accident, my mistake, have reopened it just now.

I follow exactly EXACTLY what you did in the gif. You said:

"are you sure you deleted the folder from the mounted key and not from winRE's registry?"

What do you mean by this? When I said I deleted the folder, I technically meant I deleted the KEY. What do you mean by mounted key and winRE's registry? Is there another place I should delete it from too, just in case?

Just like in the gif, I am in winRE and directed (exactly like you did) to:

Computer\HKEY_LOCAL_MACHINE\asd\Microsoft\WindowsNT\CurrentVersion\Image File Execution Options\

and I deleted the only KEY I could see, winlogon.exe. I right clicked winlogon.exe and clicked Delete.

I do not have any antiviruses installed.

**Comment by namazso** [comment]
if you indeed did delete the one inside the `asd` key it should be fine. Could you do the usual `sfc /scannow` in case it's unrelated problems?
also i have to ask, you did the other steps from OP *after* the suggested solution didn't work, right? thise can break stuff on their own occasionally

> Could Systemsettings.exe be causing the problem?

nah, it's normal to possibly have some of the folders, the installer only ever touches "VerifierDlls" and "GlobalFlag" of anything, creating folders as needed

> Also after not rebooting the first time, I then went back into the registry and did:
> New > Key > named it winlogon.exe > Left it all as default, didn't touch anything else. I thought maybe the absence of winlogon.exe after deleting it, is what caused the problem. But it didn't do anything, does Windows contain winlogon.exe by default?
It shouldn't but it doesn't actually matter

**Comment by namazso** [comment]
Yeah that's a winlogon.exe crash loop, shows that you somehow didn't actually manage to uninstall it from registry (dunno how or why).
I'll compile a no-op SecureUxTheme.dll you could use instead of the real one

**Comment by Jameel10100** [comment]
![IMG_20211020_181145](https://user-images.githubusercontent.com/41630454/138139955-935f0dab-36c4-41bd-ab45-c31315ddf611.jpg)

**Comment by Jameel10100** [comment]
winlogon.exe contains nothing, except the default REG_SZ key (as mentioned before).
And the SystemSettings.exe contains only the default REG_SZ key and "MitigationOptions" REG_QWORD key

**Comment by Jameel10100** [comment]
I just copied it into the directory. I triple-checked to make sure it's in there.

Rebooted but no success. Still a black screen

**Comment by Jameel10100** [comment]
I just found this video:

https://youtu.be/s8ABl5WFmPw

Do you recommend I try the steps in this video?
