### ISSUE TITLE
Themed elements remain after system restore

### ISSUE THREAD

**Issue by amzon-ex** [namazso/SecureUxTheme#81]
I used the software for some time to try out a few themes and only used `Rename DefaultColors` option. After trying out a few things, I performed a System Restore using a restore point created before using the software. However, even after System Restore, some menus, context menus and dialog boxes seem to be still themed and hence the colors appear weird. I did all of this in WIndows 10. After restore, a day or two later I upgraded to Win 11. However, the issue persists! 
How can I fix this?

**Comment by namazso** [comment]
Just reapply the default theme from Themes or in Theme Tool and that should be enough.

**Comment by amzon-ex** [comment]
> Just reapply the default theme from Themes or in Theme Tool and that should be enough.

That did fix my issue! Thank you so much. Closing this.
