### ISSUE TITLE
Patch button greyed out. Previous fix doesnt work.

### ISSUE THREAD

**Issue by GordeyGG** [namazso/SecureUxTheme#83]
1638338217814 > Version v2.1.2
1638338217814 > Running on 10.0.19042 flavor F
1638338217815 > MainDialog: is_elevated 1
1638338217816 > Session user: Fazeb Process user: Fazeb
1638338217833 > UpdatePatcherState: file_has_content 1 file_is_same 1 file_error 0 is_loaded 1
1638338219858 > SelectTheme: pTheme->GetVisualStyle failed with 80070002
I place themes in correct folder: Windows\Resources\Themes

**Comment by namazso** [comment]
Post your Themes folder

**Comment by GordeyGG** [comment]
https://drive.google.com/drive/folders/1G6N5V3E89Ps4X4WvS78wKFJJZDwJWaqb?usp=sharing

**Comment by GordeyGG** [comment]
> Post your Themes folder

https://drive.google.com/drive/folders/1G6N5V3E89Ps4X4WvS78wKFJJZDwJWaqb?usp=sharing

**Comment by namazso** [comment]
You moved the msstyles our of the folders. You shouldn't do that, the folder should look something like this:
```
Themes/
├── BIB3 WIN.theme
└── BIB3/
    └── BIB3 WIN.msstyles
```

**Comment by GordeyGG** [comment]
> You moved the msstyles our of the folders. You shouldn't do that, the folder should look something like this:
> 
> ```
> Themes/
> ├── BIB3 WIN.theme
> └── BIB3/
>     └── BIB3 WIN.msstyles
> ```

This problem with whole themes. Systems themes too

**Comment by namazso** [comment]
That is not really possible as system themes don't need to be patched. Also the Patch button thing is just a sideeffect, the real error is `SelectTheme: pTheme->GetVisualStyle failed with 80070002`

**Comment by GordeyGG** [comment]
> That is not really possible as system themes don't need to be patched. Also the Patch button thing is just a sideeffect, the real error is `SelectTheme: pTheme->GetVisualStyle failed with 80070002`

I tried the method you writed. It's doesnt helped me

**Comment by namazso** [comment]
In that case I can't help you as this error simply comes from windows and is not related to SecureUxTheme. The themes (after fixing the folder problems) work on my test VM.
