### ISSUE TITLE
Installing main hook failed.Error:Access Denied

### ISSUE THREAD

**Issue by nkfeiyang** [namazso/SecureUxTheme#84]
I am using Windows 11 Pro, 21H1, OS version 22000.348

When I run as admin, and click "install", but it seems failed.
![capture_20211205182457304](https://user-images.githubusercontent.com/338547/144742724-b5d61869-5b39-4367-858b-a70245e87a8c.jpg)

**Comment by nkfeiyang** [comment]
I am using Windows 11 Pro, 21H1, OS version 22000.348

**Comment by namazso** [comment]
Any antivirus used?

**Comment by namazso** [comment]
Closing due to lack of response.
