### ISSUE TITLE
Command line parameters.

### ISSUE THREAD

**Issue by boromyr** [namazso/SecureUxTheme#86]
Hi, is it possible to add command line parameters to start the program in custom scripts? 
Application example: change theme to [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) in personal script.

**Comment by namazso** [comment]
well, so far the intended way to accomplish that was to simply write your own program based on snippets from here. what do you think would be a good set of arguments to have?

**Comment by boromyr** [comment]
I'll give you an example: uxtheme.exe "C:\path\theme.msstyle"  -b(ignore background) -c(ignore cursor) -s(ignore sound) etc. 
Default: don't ignore anything.
Very simple but effective, what do you think?

**Comment by namazso** [comment]
I can't set msstyles, only themes. I also only know their display name, which may also change per locale. The rest of the functions are unstable across versions. I could also potentially use [this function](https://github.com/namazso/SecureUxTheme/blob/master/ThemeTool/interfaces.h#L144) to set a theme by path, but i never tried that

**Comment by boromyr** [comment]
Even "C:\path\theme.theme"  is fit for purpose. In fact, it's actually better because it's more complete.

**Comment by EnhancedJax** [comment]
Bump

**Comment by namazso** [comment]
This will not be implemented, I opted to go with a library and C FFI interface. You can track that issue at #120. You will be able to implement the command line interface of your choice on top of that.

**Comment by BinToss** [comment]
I writing my own AutoDarkMode script when I stumbled upon this. A shame it won't be implemented.
I suppose ADM will have to import or invoke more of SecureUxTheme to support truly dark themes.

**Comment by namazso** [comment]
With the C interface you can just write a PowerShell script with whatever CLI you want. PS has been a part of Windows since Windows 7, therefore available everywhere where SecureUxTheme is.
