### ISSUE TITLE
Settings app slow

### ISSUE THREAD

**Issue by TraySSan** [namazso/SecureUxTheme#87]
Hooking the settings app on Windows 11 build 2200.376 causes it to become unbearably slow. Furthermore, this slowness in turn causes Windows search to, as they say, shit its pants. It either stops working completely or takes a solid 30s to pop up. I'd go ahead and say hooking settings is a exclamation mark item on Windows 11. Definitely on this build.

**Comment by TraySSan** [comment]
Okay, I'm struggling to replicate the search bug now. Perhaps an update fixed it? Anyway, the sluggishness still remains. When the settings app lags, my CPU usage skyrockets as well, which is interesting I guess.

**Comment by namazso** [comment]
this is caused by app verifier enabling heap debugger. the solution for now is to not hook the settings app

**Comment by ilovetacos123** [comment]
Hey there! I have the same problem as you. I know the owner of this theme tool replied to you with the fix (and yes I did hook the settings app), the problem is... How do I reinstall this theme tool? It will be greatly appreciated if you replied to me with the reinstall process. Thanks!

P.S: I have a theme currently applied do I revert back to the normal windows theme before uninstalling? (Btw sorry for my bad English I live in Malaysia)

**Comment by namazso** [comment]
@[ilovetacos123](https://github.com/ilovetacos123)

Simply click install with the intended configuration, it actually uninstalls and reinstalls in one go.

**Comment by leemunhei123** [comment]
> @[ilovetacos123](https://github.com/ilovetacos123)
> 
> Simply click install with the intended configuration, it actually uninstalls and reinstalls in one go.

How do I do that? When I launch ThemeTool.exe I don't see "install with the intended configuration" do I have to click on the install button again?

**Comment by namazso** [comment]
@leemunhei123 that is precisely what you have to do, yes. 

> And yes I changed my name because I don't really like that name and I kept that name for a long time.

I'm using a browser plugin which replaces names with usernames so I didn't even notice it.

**Comment by namazso** [comment]
1. no
2. no

**Comment by leemunhei123** [comment]
> 1. no
> 2. no

Alright! I'm doing it right now thanks for your help :)

**Comment by leemunhei123** [comment]
> 1. no
> 2. no

Thank you! It actually worked.

**Comment by namazso** [comment]
Glad it worked. Also, closing due to no response from original OP.
