### ISSUE TITLE
After W11 Insider 22543 update, Task Manager colors in custom theme changed to be too dark to read

### ISSUE THREAD

**Issue by akaitori221** [namazso/SecureUxTheme#91]
This is the custom theme I have on W11 --> https://www.deviantart.com/niivu/art/xTheme-for-Windows-10-816289887

It has a collection of themes, the one I patched & applied is called "xLinux.msstyles".

My fav thing about this custom theme is that it has a task manager dark theme. Normally I update Windows with no issues when I had it applied before, but when I updated to the new insider 22543 yesterday, task manager colors turned too dark to read:

![Capture](https://user-images.githubusercontent.com/66203372/151679762-a29c96f0-a465-4c45-beae-f776a7ac91fa.PNG)

I tried uninstalling & installing multiple times, but the issue still persists, the rest of the theme is not affected thankfully, just the task manager.

**Comment by namazso** [comment]
most likely a theme issue

**Comment by akaitori221** [comment]
thanks for confirming, sad face lol

**Comment by Basic6969** [comment]
> most likely a theme issue

nah, the themes in the insider builds are broken.

**Comment by namazso** [comment]
Works on the actual 22H2 release:

![image](https://github.com/namazso/SecureUxTheme/assets/8676443/f6cc1664-c336-4bd9-a23f-4191a730230c)
