### ISSUE TITLE
ThemeTool doesn't apply every change that a theme makes

### ISSUE THREAD

**Issue by Alpher-Dark** [namazso/SecureUxTheme#97]
When I try to apply a custom theme, only the colors get applied. The patch button is greyed out. When I clock on a custom theme, I get this error: 1646245754664 > SelectTheme: pTheme->GetVisualStyle failed with 80070002. I gave the app administrator rights, so there shouldn't be a problem about that. What's the problem? Is there a fix? I've already looked through some issues like #19 and others that had similar issues, but no fix worked.

**Comment by namazso** [comment]
You installed the theme incorrectly (see faq entry).

If you still think you didn't, post your Themes folder

**Comment by Alpher-Dark** [comment]
Yes I installed the theme correctly (copied the .theme files(s) into Windows/Resources/Themes)

**Comment by Alpher-Dark** [comment]
there are no .msstyle files

**Comment by namazso** [comment]
Then that's all there is to the theme and the behavior is normal. Themes without custom visual styles don't need this tool, or patching.

**Comment by Alpher-Dark** [comment]
ohhhh. But for the guy that showed this tutorial visual styles were changed and there were no .msstyle files

**Comment by namazso** [comment]
post link

**Comment by Alpher-Dark** [comment]
These are the themes: https://www.deviantart.com/niivu/art/BIB3-for-Windows-886441919
This is the video: https://www.youtube.com/watch?v=eIOAtcuK8bU

**Comment by Alpher-Dark** [comment]
btw sorry but I just realized where the .msstyle files are

**Comment by namazso** [comment]
yeah, they're there in a folder just as i said in https://github.com/namazso/SecureUxTheme/issues/97#issuecomment-1057275715

![image](https://user-images.githubusercontent.com/8676443/156431630-12d905c1-c4d5-47d4-baeb-39c57399b342.png)

**Comment by Alpher-Dark** [comment]
I dropped the .msstyle and their accompanying .theme files in the folder necessary, but there are still no other visual effects

**Comment by namazso** [comment]
You'll need to reapply, this time patch button should work too.

And just to clarify, this is how your Themes folder looks like, right?

![image](https://user-images.githubusercontent.com/8676443/156432270-ea7735f4-55b7-429c-9df2-77e4241b9c32.png)

**Comment by Alpher-Dark** [comment]
OHH I was supposed to put the whole BIB folder into the Themes folder. I think this cleared some things up. I'll try and tell you if this works! Thanks!

**Comment by Alpher-Dark** [comment]
Yeah this fixed it for me. Thanks for the help and sorry for the trouble!
