### ISSUE TITLE
ERROR: CoCreateinstance failed, hr = 80040154

### ISSUE THREAD

**Issue by juninhoo266** [namazso/SecureUxTheme#98]
im getting this error even after patching windows.
im using windows 11 pro. thanks

**Comment by namazso** [comment]
Did you attempt using any other patcher before? I saw this happen on corrupted systems.

**Comment by juninhoo266** [comment]
no. i tried only after the first error. but it didnt fix.

**Comment by namazso** [comment]
Interesting. are you on insider maybe?
in either case, can you send "uxinit.dll" and "themeui.dll" from your system32 folder?

**Comment by juninhoo266** [comment]
[dlls.zip](https://github.com/namazso/SecureUxTheme/files/8176617/dlls.zip)

**Comment by namazso** [comment]
These files are visibly patched on disk:

![image](https://user-images.githubusercontent.com/8676443/156539116-7b373adb-d412-422c-8743-596b9f9102c5.png)

Only unmodified Windows dlls are supported by this project.

**Comment by juninhoo266** [comment]
as i told you before, i used another patch to try to make this work, since it was not working before.
so there is no fix?

**Comment by namazso** [comment]
Get `sfc /scannow` to pass without an error, then I'll look at it again. This issue is usually the sign of a corrupted dll (often an outdated patched or unpatched one being copied on top). As long as your system is in some unknown state, I can't do anything that isn't just a waste of my time.

**Comment by juninhoo266** [comment]
i dont want you to waste your time...
i just wanted to fix it because i want to use your tool.
also, if something is happening, it could help you to fix it and improve your tool too, avoiding more issues in the future.
ill do what you are saying then.
thanks for the help.

**Comment by juninhoo266** [comment]
it is working now after using sfc /scannow.
thanks and sorry to bother.
